[build]
  publish = "portfolio/build"
  command = "cd portfolio && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
