const LanguagePack = {
  en: {
    // Welcome Page
    'w-0': 'Welcome to Portfolio',
    'w-0-1': 'Welcome to',
    'w-0-2': 'My Portfolio',
    'w-0-3': 'Experience',
    'w-1': 'Choose your preferred theme to get started',
    'w-2': 'Light Mode',
    'w-3': 'Clean and bright interface perfect for daytime use',
    'w-4': 'Dark Mode',
    'w-5': 'Easy on the eyes, perfect for low-light environments',
    'w-6': 'You can change this setting anytime in the app',
    'w-7': 'Detected language:',
    'w-8': 'Close',
    
    // Main Page
    'm-0': "Hi, I'm John Doe",
    'm-0-0': 'Frontend Developer',
    'm-1': 'Full Stack Developer & UI/UX Designer creating exceptional digital experiences',
    'm-2': 'View My Work',
    'm-3': 'Download CV',
    'm-4': 'Projects',
    'm-5': 'Awards',
    'm-6': 'Happy Clients',
    'm-7': 'Years Experience',
    'm-8': 'Featured Projects',
    'm-9': 'Skills & Technologies',
    'm-10': "Let's Work Together",
    'm-11': 'Have a project in mind? I\'d love to hear about it. Send me a message and let\'s discuss how we can bring your ideas to life.',
  },
  yt: {
    // Welcome Page
    'w-0': 'Bienvenue au Portfolio',
    'w-0-1': 'Bienvenue à',
    'w-0-2': 'Mon Portfolio',
    'w-0-3': 'Expérience',
    'w-1': 'Choisissez votre thème préféré pour commencer',
    'w-2': 'Mode Clair',
    'w-3': 'Interface propre et lumineuse parfaite pour une utilisation diurne',
    'w-4': 'Mode Sombre',
    'w-5': 'Facile pour les yeux, parfait pour les environnements à faible luminosité',
    'w-6': 'Vous pouvez modifier ce paramètre à tout moment dans l\'application',
    'w-7': 'Langue détectée:',
    'w-8': 'Fermer',
    
    // Main Page
    'm-0': 'Salut, je suis John Doe',
    'm-0-0': 'Développeur Frontend',
    'm-1': 'Développeur Full Stack & Designer UI/UX créant des expériences numériques exceptionnelles',
    'm-2': 'Voir Mon Travail',
    'm-3': 'Télécharger CV',
    'm-4': 'Projets',
    'm-5': 'Récompenses',
    'm-6': 'Clients Satisfaits',
    'm-7': 'Années d\'Expérience',
    'm-8': 'Projets en Vedette',
    'm-9': 'Compétences & Technologies',
    'm-10': 'Travaillons Ensemble',
    'm-11': 'Vous avez un projet en tête ? J\'aimerais en entendre parler. Envoyez-moi un message et discutons de la façon dont nous pouvons donner vie à vos idées.',
  },
  jp: {
    // Welcome Page
    'w-0': 'ポートフォリオへようこそ',
    'w-0-1': 'ようこそ',
    'w-0-2': 'ポートフォリオ',
    'w-0-3': '経験',
    'w-1': '開始するには、お好みのテーマを選択してください',
    'w-2': 'ライトモード',
    'w-3': '昼間の使用に最適なクリーンで明るいインターフェース',
    'w-4': 'ダークモード',
    'w-5': '目に優しく、低照度環境に最適',
    'w-6': 'この設定はアプリ内でいつでも変更できます',
    'w-7': '検出された言語:',
    'w-8': '閉じる',
    
    // Main Page
    'm-0': 'こんにちは、私はJohn Doeです',
    'm-0-0': 'フロントエンド開発者',
    'm-1': '例外的なデジタル体験を作成するフルスタック開発者 & UI/UXデザイナー',
    'm-2': '私の作品を見る',
    'm-3': '履歴書をダウンロード',
    'm-4': 'プロジェクト',
    'm-5': '受賞',
    'm-6': '満足したクライアント',
    'm-7': '年の経験',
    'm-8': '注目のプロジェクト',
    'm-9': 'スキル & 技術',
    'm-10': '一緒に働きましょう',
    'm-11': 'プロジェクトのアイデアがありますか？聞いてみたいです。メッセージを送って、アイデアを現実にする方法について話し合いましょう。',
  },
  cn: {
    // Welcome Page
    'w-0': '欢迎来到作品集',
    'w-0-1': '欢迎来到',
    'w-0-2': '我的作品集',
    'w-0-3': '体验',
    'w-1': '选择您喜欢的主题开始',
    'w-2': '浅色模式',
    'w-3': '适合白天使用的清洁明亮界面',
    'w-4': '深色模式',
    'w-5': '护眼，适合低光环境',
    'w-6': '您可以随时在应用中更改此设置',
    'w-7': '检测到的语言:',
    'w-8': '关闭',
    
    // Main Page
    'm-0': '你好，我是John Doe',
    'm-0-0': '前端开发者',
    'm-1': '创造卓越数字体验的全栈开发者 & UI/UX设计师',
    'm-2': '查看我的作品',
    'm-3': '下载简历',
    'm-4': '项目',
    'm-5': '奖项',
    'm-6': '满意客户',
    'm-7': '年经验',
    'm-8': '精选项目',
    'm-9': '技能 & 技术',
    'm-10': '让我们一起工作',
    'm-11': '有项目想法吗？我很想听听。给我发消息，让我们讨论如何将您的想法变为现实。',
  },
  de: {
    // Welcome Page
    'w-0': 'Willkommen zum Portfolio',
    'w-0-1': 'Willkommen zu',
    'w-0-2': 'Mein Portfolio',
    'w-0-3': 'Erfahrung',
    'w-1': 'Wählen Sie Ihr bevorzugtes Theme zum Starten',
    'w-2': 'Heller Modus',
    'w-3': 'Saubere und helle Oberfläche perfekt für die Tagesnutzung',
    'w-4': 'Dunkler Modus',
    'w-5': 'Augenfreundlich, perfekt für schwach beleuchtete Umgebungen',
    'w-6': 'Sie können diese Einstellung jederzeit in der App ändern',
    'w-7': 'Erkannte Sprache:',
    'w-8': 'Schließen',
    
    // Main Page
    'm-0': 'Hallo, ich bin John Doe',
    'm-0-0': 'Frontend-Entwickler',
    'm-1': 'Full Stack Entwickler & UI/UX Designer, der außergewöhnliche digitale Erfahrungen schafft',
    'm-2': 'Meine Arbeit Ansehen',
    'm-3': 'CV Herunterladen',
    'm-4': 'Projekte',
    'm-5': 'Auszeichnungen',
    'm-6': 'Zufriedene Kunden',
    'm-7': 'Jahre Erfahrung',
    'm-8': 'Ausgewählte Projekte',
    'm-9': 'Fähigkeiten & Technologien',
    'm-10': 'Lassen Sie uns Zusammenarbeiten',
    'm-11': 'Haben Sie eine Projektidee? Ich würde gerne davon hören. Senden Sie mir eine Nachricht und lassen Sie uns besprechen, wie wir Ihre Ideen verwirklichen können.',
  },
  ko: {
    // Welcome Page
    'w-0-1': '포트폴리오에 오신 것을 환영합니다.',
    'w-0-2': '언어를 변경하시려면 국가 아이콘을 클릭하세요.',
    'w-0-3': '테마를 선택해주세요.',
    'w-1': '시작하려면 선호하는 테마를 선택하세요',
    'w-2': '라이트 모드',
    'w-3': '낮 시간 사용에 완벽한 깔끔하고 밝은 인터페이스',
    'w-4': '다크 모드',
    'w-5': '눈에 편안하고 어두운 환경에 완벽한 모드',
    'w-6': '언제든지 앱에서 이 설정을 변경할 수 있습니다',
    'w-7': '감지된 언어:',
    'w-8': '닫기',

    'h-1': '포트폴리오',
    
    // Main Page
    'm-0': '안녕하세요,',
    'm-0-0': '프론트엔드 개발자 유현우 입니다',
    'm-0-1': '알아보기 까지  ',
    'm-0-2': '✓ 완료됨',
    'm-0-3': '스와이프하여 시작',
    'm-1': '뛰어난 디지털 경험을 만드는 풀스택 개발자 & UI/UX 디자이너',
    'm-2': '내 작품 보기',
    'm-3': '이력서 다운로드',
    'm-4': '프로젝트',
    'm-5': '수상',
    'm-6': '만족한 클라이언트',
    'm-7': '년 경력',
    'm-8': '주요 프로젝트',
    'm-9': '기술 & 도구',
    'm-10': '함께 일해요',
    'm-11': '프로젝트 아이디어가 있으신가요? 듣고 싶습니다. 메시지를 보내주시면 아이디어를 현실로 만드는 방법에 대해 논의해보겠습니다.',

    
    'DES-0': '유현우',
    'DES-5': '스택',
  },
};

export default LanguagePack;