const LanguagePack = {
  en: {
    "w-0-1": "Welcome to the Portfolio.",
    "w-0-2": "Click the country icon to change the language.",
    "w-0-3": "Please select a theme.",
    "w-1": "Choose your preferred theme to get started",
    "w-2": "Light Mode",
    "w-3": "A clean, bright interface perfect for daytime use",
    "w-4": "Dark Mode",
    "w-5": "A mode that's easy on the eyes, perfect for dark environments",
    "w-6": "You can change this setting in the app at any time",
    "w-7": "Detected Language:",
    "w-8": "Close",
    "h-1": "Portfolio",
    "m-0": "Hello, I'm Hyunwu Yu,",
    "m-0-0": "Frontend Developer",
    "m-0-1": "Until we get to know each other ",
    "m-0-2": "✓ Completed",
    "m-0-3": "Swipe to Start",
    "m-1": "I love to create outstanding digital experiences and design developments.",
    "m-2": "View My Work",
    "m-3": "Download CV",
    "m-4": "Projects",
    "m-5": "Awards",
    "m-6": "Satisfied Clients",
    "m-7": "Years of Experience",
    "m-8": "Main Projects",
    "m-9": "Skills & Tools",
    "m-10": "Let's Work Together",
    "m-11": "Have a project idea? I'd love to hear it. Send me a message, and we can discuss how to bring your idea to life.",
    "DES-0": "Hyunwu Yu",
    "DES-5": "Stack",
    "c-0": "Contact",
    "c-1": "Name *",
    "c-2": "Email *",
    "c-3": "Phone Number (Optional)",
    "c-4": "Message *",
    "c-5": "Send",
    "c-6": "Sending...",
    "c-7": "Your message was sent successfully! I will get back to you as soon as possible.",
    "c-8": "An error occurred while sending. Please try again.",
    "c-9": "Please enter your name",
    "c-10": "Please enter your email",
    "c-11": "Please enter your phone number",
    "c-12": "Please enter a message",
    "c-13": "Optional",
    "c-14": "AWS Lambda Function executing...",
    "scroll-to-top": "Scroll to Top",
    "p-0": "All",
    "p-1": "Main",
    "p-2": "Side",
    "p-3": "Completed",
    "p-4": "In Progress",
    "p-5": "Planned",
    "p-6": "Learn More",
    "p-7": "View GitHub Code",
    "p-8": "View Live Demo",
    "p-9": "View More",
    "p-10": "Collapse",
    
    // Projects Section Additional Keys
    "p-11": "Projects",
    "p-12": "Check out various projects",
    "p-13": "Project Type",
    "p-14": "Completion Status",
    "p-15": "more",
    
    // Project Detail Modal Keys
    "pd-1": "GitHub Code View",
    "pd-2": "Live Demo View",
    "pd-3": "Project Information",
    "pd-4": "Development Team:",
    "pd-5": "people",
    "pd-6": "Role:",
    "pd-7": "Tech Stack",
    "pd-8": "Project Overview",
    "pd-9": "Key Features",
    "pd-10": "Challenges",
    "pd-11": "Solutions",
    
    // Project Badge Labels
    "badge-main": "Main Project",
    "badge-latest": "Latest Project", 
    "badge-side": "Side Project",
    "badge-completed": "Completed",
    "badge-in-progress": "In Progress",
    "b-0": "Latest Blog Posts",
    "b-1": "Read More",
    "b-2": "Click on the Notion shortcut for detailed content",
    "b-3": "Notion Shortcut",
    "s-0": "Languages & Frameworks",
    "s-1": "Libraries",
    "s-2": "Environment & Deployment",
    "s-3": "Design & Collaboration",
    
    // Stack Filter Labels
    "stack-all": "All",
    "stack-language": "Languages & Frameworks",
    "stack-library": "Libraries",
    "stack-deployment": "Environment & Deployment",
    "stack-design": "Design & Collaboration",
    "proj-1-title": "The Clipo Project",
    "proj-1-desc": "A social media platform portfolio using React, Tailwind CSS, and TypeScript.",
    "proj-1-short": "Personal Portfolio Website",
    "proj-1-overview": "A responsive website for a personal portfolio, featuring dark/light mode, Access Token, and Refresh Token. I tried to make it as if I were developing a social media platform with a friend for real-world practice.",
    "proj-1-feature-1": "Authentication and Token Management System",
    "proj-1-feature-2": "Redux-based Multi-nested Modal System",
    "proj-1-feature-3": "Core Social Media Features",
    "proj-1-feature-4": "UI Components and Design System",
    "proj-1-feature-5": "Data and State Management",
    "proj-1-feature-6": "Real-time Functionality",
    "proj-1-challenge": "Optimistic updates and data synchronization / Collaboration with the backend.",
    "proj-1-solution": "Utilized React-query for synchronization by fetching previous queries upon network errors.",
    "proj-1-role": "Frontend / Planner",
    
    // Project 2 - Football Video Automation
    "proj-2-overview": "A football-themed video automation system created out of passion for football. This weekly automated video system fetches match schedules and uses AWS Lambda scheduling to fetch match data via Telegram Bot.",
    "proj-2-feature-1": "Football API data fetching",
    "proj-2-feature-2": "Python data processing and Telegram Bot integration",
    "proj-2-feature-3": "AWS Lambda scheduling and execution",
    "proj-2-feature-4": "AWS S3 file storage",
    "proj-2-feature-5": "Google Spreadsheet integration",
    "proj-2-feature-6": "Movie.py video automation",
    "proj-2-feature-7": "YouTube API integration",
    "proj-2-challenge": "Movie.py package adaptation, AWS Step Function runtime error handling",
    "proj-2-solution": "Adapted using Movie.py Official Documentation, identified error types in Step Function and implemented runtime error handling",
    "proj-2-role": "Solo Developer",
    
    // Project 3 - Calendar Project
    "proj-3-overview": "A fully-featured online shopping mall platform including user authentication, payment system, and admin dashboard.",
    "proj-3-feature-1": "User authentication and permission management",
    "proj-3-feature-2": "Product search and filtering",
    "proj-3-feature-3": "Shopping cart and wishlist",
    "proj-3-feature-4": "Stripe payment system",
    "proj-3-feature-5": "Admin dashboard",
    "proj-3-feature-6": "Real-time inventory management",
    "proj-3-challenge": "High-traffic processing and payment security",
    "proj-3-solution": "Built secure payment system using Redis caching and Stripe security API",
    "proj-3-role": "Frontend Developer",
    
    // Project 4 - Job Scraper
    "proj-4-overview": "A web application that collects and integrates job postings from Korean and international job sites in real-time.",
    "proj-4-feature-1": "Integrated search across 4 job sites (Wanted, Saramin, RemoteOK, WeWorkRemotely)",
    "proj-4-feature-2": "Site-specific selective search functionality",
    "proj-4-feature-3": "Regional filtering (Seoul, Gyeonggi, Incheon, etc.)",
    "proj-4-feature-4": "Real-time job posting collection",
    "proj-4-feature-5": "CSV file download functionality",
    "proj-4-feature-6": "Mobile responsive design",
    "proj-4-feature-7": "Dynamic web scraping (Selenium)",
    "proj-4-feature-8": "API-based data collection (Wanted, RemoteOK)",
    "proj-4-feature-9": "Site-specific statistics and filtering",
    "proj-4-feature-10": "Real-time search result updates",
    "proj-4-challenge": "Handling access restrictions and dynamic content processing across various sites, ensuring stable data collection",
    "proj-4-solution": "Implemented hybrid approach using Selenium and requests, error handling and fallback mechanisms",
    "proj-4-role": "Full-stack Developer",
    
    // Project 5 - Random Chord Practice
    "proj-5-overview": "A random chord practice app for musicians, providing systematic music practice through various chord types and tempo settings. Includes voice guidance using Web Speech API and real-time tempo adjustment features.",
    "proj-5-feature-1": "Random chord generation and practice",
    "proj-5-feature-2": "Support for 17 notes (C, Db, D, Eb, E, F, Gb, G, Ab, A, Bb, B, C#, D#, F#, G#, A#)",
    "proj-5-feature-3": "Various chord types (Maj7, min7, 7, sus4, add9, etc. 50+ types)",
    "proj-5-feature-4": "Real-time tempo adjustment (1-220 BPM)",
    "proj-5-feature-5": "Beat visualization (4-beat dot animation)",
    "proj-5-feature-6": "Voice guidance system (TTS)",
    "proj-5-feature-7": "Custom chord addition/removal",
    "proj-5-feature-8": "Settings storage (Local Storage)",
    "proj-5-feature-9": "Responsive design",
    "proj-5-feature-10": "A/B form pattern selection",
    "proj-5-challenge": "Complex page navigation and maintaining beat synchronization when changing tempo in real-time",
    "proj-5-solution": "Implemented stable state management using 3-component structure (title/main/settings) and interval-based beat animation",
    "proj-5-role": "Full-stack Developer",
    
    // Project 6 - The Area
    "proj-6-overview": "A comprehensive creative platform for music, visual arts, and creators",
    "proj-6-feature-1": "Video background and logo animation",
    "proj-6-feature-2": "Music video player",
    "proj-6-feature-3": "Creator profile gallery",
    "proj-6-feature-4": "MV gallery system",
    "proj-6-feature-5": "Responsive design",
    "proj-6-feature-6": "Page routing system",
    "proj-6-challenge": "Complex animation and video processing, responsive design implementation",
    "proj-6-solution": "Dynamic UI implementation using CSS animations and React state management",
    "proj-6-role": "Full-stack Developer",
    
    // Project 7 - Cocoa Talk
    "proj-7-overview": "A website mimicking KakaoTalk's UI/UX, featuring a football-themed chat application. Implemented mobile-first responsive web design.",
    "proj-7-feature-1": "Real-time clock display functionality",
    "proj-7-feature-2": "Mobile responsive design",
    "proj-7-feature-3": "Football match schedule and live streaming section",
    "proj-7-feature-4": "Chat room list and individual chat rooms",
    "proj-7-feature-5": "Profile page (including football player information)",
    "proj-7-feature-6": "Community and search functionality",
    "proj-7-feature-7": "Font Awesome icon utilization",
    "proj-7-feature-8": "CSS animation effects",
    "proj-7-feature-9": "Mobile screen size limitation functionality",
    "proj-7-challenge": "Mobile-first design and implementing KakaoTalk's complex UI structure for web",
    "proj-7-solution": "Layout composition using CSS Grid and Flexbox, real-time functionality implementation with JavaScript, mobile screen size detection functionality",
    "proj-7-role": "Full-stack Web Developer",
    
    // Project 8 - Momentum Dashboard
    "proj-8-overview": "An all-in-one dashboard for personal productivity enhancement, integrating real-time clock, weather information, todo management, music player, quote display, and Google search functionality. Provides optimal user experience through user personalization and responsive design.",
    "proj-8-feature-1": "Real-time digital clock and date display",
    "proj-8-feature-2": "Geolocation-based current location weather information",
    "proj-8-feature-3": "OpenWeather API integration (temperature, humidity, feels-like temperature, etc.)",
    "proj-8-feature-4": "Todo list management (add, complete, delete)",
    "proj-8-feature-5": "Data permanent storage using Local Storage",
    "proj-8-feature-6": "YouTube API-based music player",
    "proj-8-feature-7": "Playlist management (play, pause, previous/next song)",
    "proj-8-feature-8": "Random quote display system",
    "proj-8-feature-9": "Google search integration",
    "proj-8-feature-10": "Time-based customized greetings",
    "proj-8-feature-11": "Time-based automatic background image changes",
    "proj-8-feature-12": "User name setting and logout functionality",
    "proj-8-feature-13": "Responsive design and animation effects",
    "proj-8-challenge": "Multiple API integration and Local Storage state management, real-time data synchronization",
    "proj-8-solution": "Stable state management implementation using modularized JavaScript structure and event-based programming",
    "proj-8-role": "Full-stack Developer",
    
    // Project 9 - Campground
    "proj-9-overview": "A web application for registering and managing campground information. Includes user authentication, campground CRUD functionality, and review system.",
    "proj-9-feature-1": "User registration/login/logout",
    "proj-9-feature-2": "Campground information registration (title, location, price, description, photos)",
    "proj-9-feature-3": "Campground list viewing and detailed information",
    "proj-9-feature-4": "Campground information editing and deletion",
    "proj-9-feature-5": "Author permission management (only own posts can be edited/deleted)",
    "proj-9-feature-6": "Review system (rating and text reviews)",
    "proj-9-feature-7": "Responsive web design (Bootstrap 5)",
    "proj-9-feature-8": "User feedback through flash messages",
    "proj-9-feature-9": "Session-based authentication system",
    "proj-9-challenge": "User authentication system implementation and permission management, MongoDB relational data processing",
    "proj-9-solution": "Authentication system construction using Passport.js and relational data query optimization through Mongoose populate",
    "proj-9-role": "Full-stack Developer",
    
    // About Me Section
    "about-title": "About Me",
    "experience-title": "💼 Experience",
    "education-title": "🎓 Education",
    "experience-btn": "💼 Experience",
    "education-btn": "🎓 Education",
    
    // Experience Data
    "exp-1-company": "Coboct (France)",
    "exp-1-position": "Website Renewal Intern",
    "exp-1-period": "2023.09 - 2023.12 (4 months)",
    "exp-1-desc-1": "Frontend UI/UX improvement using React.js and ModuleCSS",
    "exp-1-desc-2": "Applied responsive web design",
    "exp-1-desc-3": "Attempted to apply 3D effects using Three.js",
    
    "exp-2-company": "Rsupport",
    "exp-2-position": "QA Engineer",
    "exp-2-period": "2021.06 - 2022.12 (1 year 6 months)",
    "exp-2-desc-1": "Participated in development planning meetings",
    "exp-2-desc-2": "Test case writing certification",
    "exp-2-desc-3": "Participated in writing and maintaining Java Selenium automation test scripts",
    
    "exp-3-company": "Republic of Korea Army",
    "exp-3-position": "8th Division Discharge",
    "exp-3-period": "2019.04 - 2021.10",
    "exp-3-desc-1": "Developed leadership and responsibility through squad leader duties",
    "exp-3-desc-2": "Enhanced teamwork based on smooth communication skills",
    
    // Education Data
    "edu-1-school": "Korea Cyber University",
    "edu-1-major": "Software Application Major Graduation (2021-2024)",
    "edu-2-school": "Hallym University",
    "edu-2-major": "Economics Major Dropout (2018-2019)",
    
    // Blog Data
    "blog-1-title": "AccessToken RefreshToken Implementation",
    "blog-1-desc": "Learn about JWT authentication procedures by implementing access tokens and refresh tokens. Among various methods, we use refreshToken as an action to reassign when it expires after storing it in cookie values.",
    "blog-2-title": "MongoDB Data Structuring using Mongoose",
    "blog-2-desc": "While working on Campingground, I learned about mongoose that parses data objects from node.js and mongoDb. Mongoose is a module that makes it easy to parse mongoDb data into an easy-to-use object format.",
    "blog-3-title": "Implementing Nested Modals",
    "blog-3-desc": "Implement nested modals by changing the initial value of Redux to an array and distributing z-index appropriately.",
    
    // Rotating Text
    "rotating-texts": "Creative,Passionate,Aspiring,Challenging"
  },
  yt: {
      "w-0-1": "Bienvenue sur le portfolio.",
      "w-0-2": "Cliquez sur l'icône du pays pour changer de langue.",
      "w-0-3": "Veuillez sélectionner un thème.",
      "w-1": "Choisissez votre thème préféré pour commencer",
      "w-2": "Mode Clair",
      "w-3": "Une interface claire et lumineuse, parfaite pour la journée",
      "w-4": "Mode Sombre",
      "w-5": "Un mode agréable pour les yeux, parfait pour les environnements sombres",
      "w-6": "Vous pouvez modifier ce paramètre à tout moment dans l'application",
      "w-7": "Langue détectée :",
      "w-8": "Fermer",
      "h-1": "Portfolio",
      "m-0": "Bonjour, je suis Hyunwu Yu,",
      "m-0-0": "développeur Frontend",
      "m-0-1": "Jusqu'à ce que nous nous rencontrions ",
      "m-0-2": "✓ Terminé",
      "m-0-3": "Glissez pour commencer",
      "m-1": "J'adore créer des expériences numériques exceptionnelles et concevoir des développements.",
      "m-2": "Voir mon travail",
      "m-3": "Télécharger le CV",
      "m-4": "Projets",
      "m-5": "Récompenses",
      "m-6": "Clients satisfaits",
      "m-7": "Années d'expérience",
      "m-8": "Projets principaux",
      "m-9": "Technologies et outils",
      "m-10": "Travaillons ensemble",
      "m-11": "Vous avez une idée de projet ? J'aimerais l'entendre. Envoyez-moi un message et nous pourrons discuter de la manière de concrétiser votre idée.",
      "DES-0": "Hyunwu Yu",
      "DES-5": "Stack",
      "c-0": "Contact",
      "c-1": "Nom *",
      "c-2": "Email *",
      "c-3": "Numéro de téléphone (facultatif)",
      "c-4": "Message *",
      "c-5": "Envoyer",
      "c-6": "Envoi en cours...",
      "c-7": "Votre message a été envoyé avec succès ! Je vous répondrai dès que possible.",
      "c-8": "Une erreur s'est produite lors de l'envoi. Veuillez réessayer.",
      "c-9": "Veuillez entrer votre nom",
      "c-10": "Veuillez entrer votre email",
      "c-11": "Veuillez entrer votre numéro de téléphone",
      "c-12": "Veuillez entrer un message",
      "c-13": "Optionnel",
      "c-14": "Fonction AWS Lambda en cours d'exécution...",
      "scroll-to-top": "Retour en haut",
      "p-0": "Tous",
      "p-1": "Principal",
      "p-2": "Secondaire",
      "p-3": "Terminé",
      "p-4": "En cours",
      "p-5": "Prévu",
      "p-6": "En savoir plus",
      "p-7": "Voir le code GitHub",
      "p-8": "Voir la démo en direct",
      "p-9": "Voir plus",
      "p-10": "Réduire",
      "b-0": "Derniers articles de blog",
      "b-1": "Lire la suite",
      "b-2": "Cliquez sur le raccourci Notion pour le contenu détaillé",
      "b-3": "Raccourci Notion",
      "s-0": "Langages et frameworks",
      "s-1": "Bibliothèques",
      "s-2": "Environnement et déploiement",
      "s-3": "Design et collaboration",
      
      // Stack Filter Labels
      "stack-all": "Tous",
      "stack-language": "Langages et frameworks",
      "stack-library": "Bibliothèques",
      "stack-deployment": "Environnement et déploiement",
      "stack-design": "Design et collaboration",
      "proj-1-title": "Le projet Clipo",
      "proj-1-desc": "Un portfolio de plateforme de médias sociaux utilisant React, Tailwind CSS et TypeScript.",
      "proj-1-short": "Site web de portfolio personnel",
      "proj-1-overview": "Un site web réactif pour un portfolio personnel avec un mode sombre/clair, un jeton d'accès et un jeton de rafraîchissement. J'ai essayé de le faire comme si je développais une plateforme de médias sociaux avec un ami pour la pratique.",
      "proj-1-feature-1": "Système d'authentification et de gestion des jetons",
      "proj-1-feature-2": "Système de modales multi-imbriquées basé sur Redux",
      "proj-1-feature-3": "Fonctionnalités de base des médias sociaux",
      "proj-1-feature-4": "Composants d'interface utilisateur et système de design",
      "proj-1-feature-5": "Gestion des données et de l'état",
      "proj-1-feature-6": "Fonctionnalités en temps réel",
      "proj-1-challenge": "Mises à jour optimistes et synchronisation des données / collaboration avec le backend.",
      "proj-1-solution": "Utilisation de React-query pour la synchronisation en récupérant les requêtes précédentes en cas d'erreur réseau.",
      "proj-1-role": "Frontend / Planificateur",
      "proj-2-title": "Automatisation de vidéos de football",
      "proj-2-desc": "Automatisation vidéo avec Movie.py en utilisant AWS Lambda et Python.",
      "proj-2-short": "",
      "proj-2-overview": "Un système d'automatisation vidéo né de mon amour pour le football. Après la planification, le développement a commencé sur un système qui fonctionne une fois par semaine. Il planifie AWS Lambda en fonction des calendriers de match récupérés et récupère les données de match via un bot Telegram.",
      "proj-2-feature-1": "Récupération de données depuis l'API Football",
      "proj-2-feature-2": "Traitement de données en Python et intégration du bot Telegram",
      "proj-2-feature-3": "Planification et exécution d'AWS Lambda",
      "proj-2-feature-4": "Stockage de fichiers sur AWS S3",
      "proj-2-feature-5": "Intégration de Google Spreadsheet",
      "proj-2-feature-6": "Automatisation vidéo avec Movie.py",
      "proj-2-feature-7": "Intégration de l'API YouTube",
      "proj-2-challenge": "Adaptation au package Movie.py, gestion des erreurs d'exécution d'AWS Step Function.",
      "proj-2-solution": "Adaptation en se référant à la documentation officielle de Movie.py, identification et gestion des types d'erreurs dans Step Function.",
      "proj-2-role": "Développeur solo",
      "proj-3-title": "Calendrier Automatique",
      "proj-3-desc": "Plateforme de calendrier automatisée",
      "proj-3-short": "Système de planification de calendrier automatique utilisant l'API Open AI.",
      "proj-3-overview": "Une plateforme de commerce électronique entièrement fonctionnelle comprenant l'authentification des utilisateurs, un système de paiement et un tableau de bord d'administration.",
      "proj-3-feature-1": "Authentification et gestion des autorisations des utilisateurs",
      "proj-3-feature-2": "Recherche et filtrage de produits",
      "proj-3-feature-3": "Panier d'achat et liste de souhaits",
      "proj-3-feature-4": "Système de paiement Stripe",
      "proj-3-feature-5": "Tableau de bord d'administration",
      "proj-3-feature-6": "Gestion des stocks en temps réel",
      "proj-3-challenge": "Gestion du trafic élevé et sécurité des paiements.",
      "proj-3-solution": "Construction d'un système de paiement sécurisé à l'aide de la mise en cache Redis et de l'API sécurisée de Stripe.",
      "proj-3-role": "Développeur Frontend",
      "proj-4-title": "Scraper d'offres d'emploi web en Python",
      "proj-4-desc": "Un scraper web intégré pour rechercher et filtrer simultanément les offres d'emploi de plusieurs sites d'emploi.",
      "proj-4-short": "Recherche intégrée d'offres d'emploi sur Wanted, Saramin, RemoteOK et WeWorkRemotely.",
      "proj-4-overview": "Une application web qui collecte les offres d'emploi en temps réel sur des sites d'emploi coréens et internationaux et fournit une recherche intégrée.",
      "proj-4-feature-1": "Recherche intégrée sur 4 sites d'emploi (Wanted, Saramin, RemoteOK, WeWorkRemotely)",
      "proj-4-feature-2": "Fonction de recherche sélective par site",
      "proj-4-feature-3": "Filtrage par région (Séoul, Gyeonggi, Incheon, etc.)",
      "proj-4-feature-4": "Collecte d'offres d'emploi en temps réel",
      "proj-4-feature-5": "Fonction de téléchargement de fichiers CSV",
      "proj-4-feature-6": "Design responsive mobile",
      "proj-4-feature-7": "Scraping web dynamique (Selenium)",
      "proj-4-feature-8": "Collecte de données basée sur l'API (Wanted, RemoteOK)",
      "proj-4-feature-9": "Statistiques et filtrage par site",
      "proj-4-feature-10": "Mise à jour en temps réel des résultats de recherche",
      "proj-4-challenge": "Gestion des restrictions d'accès et du contenu dynamique sur divers sites, collecte de données stable.",
      "proj-4-solution": "Une approche hybride utilisant Selenium et requests, gestion des erreurs et mise en œuvre de mécanismes de repli.",
      "proj-4-role": "Développeur Full-Stack",
      "proj-5-title": "Application d'entraînement aux accords aléatoires",
      "proj-5-desc": "Un générateur d'accords aléatoires moderne et convivial pour la pratique musicale.",
      "proj-5-short": "Application web d'entraînement aux accords de musique.",
      "proj-5-overview": "Une application d'entraînement aux accords aléatoires pour les musiciens, offrant une pratique musicale systématique grâce à divers types d'accords et réglages de tempo. Comprend un guidage vocal à l'aide de l'API Web Speech et un réglage du tempo en temps réel.",
      "proj-5-feature-1": "Génération d'accords aléatoires et entraînement",
      "proj-5-feature-2": "Prise en charge de 17 notes (Do, Réb, Ré, Mib, Mi, Fa, Solb, Sol, Lab, La, Sib, Si, Do#, Ré#, Fa#, Sol#, La#)",
      "proj-5-feature-3": "Différents types d'accords (Maj7, min7, 7, sus4, add9, etc. plus de 50 types)",
      "proj-5-feature-4": "Réglage du tempo en temps réel (1-220 BPM)",
      "proj-5-feature-5": "Visualisation du rythme (animation de points à 4 temps)",
      "proj-5-feature-6": "Système de guidage vocal (TTS)",
      "proj-5-feature-7": "Ajouter/supprimer des accords personnalisés",
      "proj-5-feature-8": "Enregistrer les paramètres (Stockage local)",
      "proj-5-feature-9": "Design réactif",
      "proj-5-feature-10": "Sélection du modèle de formulaire A/B",
      "proj-5-challenge": "Navigation de page complexe et maintien de la synchronisation du rythme lors des changements de tempo en temps réel.",
      "proj-5-solution": "Mise en œuvre d'une gestion d'état stable avec une structure à 3 composants (titre/principal/paramètres) et une animation de rythme basée sur des intervalles.",
      "proj-5-role": "Développeur Full-Stack",
      "proj-6-title": "The Area - Plateforme créative",
      "proj-6-desc": "Une plateforme créative complète pour la musique, les visuels et les créateurs.",
      "proj-6-short": "Plateforme créative",
      "proj-6-overview": "Une plateforme créative complète pour la musique, les arts visuels et les créateurs.",
      "proj-6-feature-1": "Arrière-plan vidéo et animation de logo",
      "proj-6-feature-2": "Lecteur de clips vidéo musicaux",
      "proj-6-feature-3": "Galerie de profils de créateurs",
      "proj-6-feature-4": "Système de galerie de clips vidéo",
      "proj-6-feature-5": "Design réactif",
      "proj-6-feature-6": "Système de routage de page",
      "proj-6-challenge": "Animations complexes et traitement vidéo, mise en œuvre d'un design réactif.",
      "proj-6-solution": "Mise en œuvre d'une interface utilisateur dynamique avec des animations CSS et la gestion de l'état de React.",
      "proj-6-role": "Développeur Full-Stack",
      "proj-7-title": "Site web de l'application de football",
      "proj-7-desc": "Un site web mobile clone de KakaoTalk sur le thème du football, créé avec HTML, CSS et JavaScript.",
      "proj-7-short": "Clone d'application de chat sur le thème du football.",
      "proj-7-overview": "Un site web imitant l'UI/UX de KakaoTalk, une application de chat sur le thème du football. Met en œuvre un design web réactif avec une approche mobile-first.",
      "proj-7-feature-1": "Affichage de l'horloge en temps réel",
      "proj-7-feature-2": "Design responsive mobile",
      "proj-7-feature-3": "Section des calendriers de matchs de football et de la diffusion en direct",
      "proj-7-feature-4": "Liste des salles de discussion et salles de discussion individuelles",
      "proj-7-feature-5": "Page de profil (y compris les informations sur les joueurs de football)",
      "proj-7-feature-6": "Fonctions de communauté et de recherche",
      "proj-7-feature-7": "Utilisation des icônes Font Awesome",
      "proj-7-feature-8": "Effets d'animation CSS",
      "proj-7-feature-9": "Fonction de limitation de la taille de l'écran mobile",
      "proj-7-challenge": "Conception mobile-first et mise en œuvre de la structure complexe de l'interface utilisateur de KakaoTalk sur le web.",
      "proj-7-solution": "Composition de la mise en page à l'aide de CSS Grid et Flexbox, mise en œuvre de fonctions en temps réel avec JavaScript, ajout d'une fonction de détection de la taille de l'écran mobile.",
      "proj-7-role": "Développeur web Full-Stack",
      "proj-8-title": "Tableau de bord Momentum",
      "proj-8-desc": "Une application web de tableau de bord tout-en-un pour augmenter la productivité personnelle.",
      "proj-8-short": "Tableau de bord personnel basé sur le web.",
      "proj-8-overview": "Un tableau de bord tout-en-un pour augmenter la productivité personnelle, une application web moderne qui intègre une horloge en temps réel, des informations météorologiques, la gestion des tâches, un lecteur de musique, l'affichage de citations et la recherche Google. Offre une expérience utilisateur optimale grâce à la personnalisation et au design réactif.",
      "proj-8-feature-1": "Affichage de l'horloge numérique et de la date en temps réel",
      "proj-8-feature-2": "Informations météorologiques de l'emplacement actuel basées sur la géolocalisation",
      "proj-8-feature-3": "Intégration de l'API OpenWeather (température, humidité, température ressentie, etc.)",
      "proj-8-feature-4": "Gestion de la liste de tâches (ajouter, terminer, supprimer)",
      "proj-8-feature-5": "Persistance des données à l'aide du stockage local",
      "proj-8-feature-6": "Lecteur de musique basé sur l'API YouTube",
      "proj-8-feature-7": "Gestion de la liste de lecture (lecture, pause, précédent/suivant)",
      "proj-8-feature-8": "Système d'affichage de citations aléatoires",
      "proj-8-feature-9": "Intégration de la recherche Google",
      "proj-8-feature-10": "Salutations personnalisées en fonction de l'heure",
      "proj-8-feature-11": "Changement automatique de l'image de fond en fonction de l'heure",
      "proj-8-feature-12": "Réglage du nom d'utilisateur et fonction de déconnexion",
      "proj-8-feature-13": "Design réactif et effets d'animation",
      "proj-8-challenge": "Intégration de plusieurs API et gestion de l'état avec le stockage local, synchronisation des données en temps réel.",
      "proj-8-solution": "Mise en œuvre d'une gestion d'état stable avec une structure JavaScript modularisée et une programmation événementielle.",
      "proj-8-role": "Développeur Full-Stack",
      "proj-9-title": "Système de gestion de camping",
      "proj-9-desc": "Une application web pour l'enregistrement, la visualisation, la modification et la suppression d'informations sur les campings, ainsi qu'un système d'évaluation.",
      "proj-9-short": "Plateforme intégrée de gestion de camping.",
      "proj-9-overview": "Une application web pour enregistrer et gérer les informations sur les campings. Comprend l'authentification des utilisateurs, les fonctions CRUD pour les campings et un système d'évaluation.",
      "proj-9-feature-1": "Inscription/connexion/déconnexion des utilisateurs",
      "proj-9-feature-2": "Enregistrement des informations sur le camping (titre, emplacement, prix, description, photo)",
      "proj-9-feature-3": "Visualisation de la liste des campings et des détails",
      "proj-9-feature-4": "Modification et suppression des informations sur le camping",
      "proj-9-feature-5": "Gestion des autorisations de l'auteur (seuls les propres messages peuvent être modifiés/supprimés)",
      "proj-9-feature-6": "Système d'évaluation (note et commentaire textuel)",
      "proj-9-feature-7": "Design web réactif (Bootstrap 5)",
      "proj-9-feature-8": "Retour d'information de l'utilisateur via des messages flash",
      "proj-9-feature-9": "Système d'authentification basé sur la session",
      "proj-9-challenge": "Mise en œuvre d'un système d'authentification des utilisateurs et gestion des autorisations, traitement des données relationnelles dans MongoDB.",
      "proj-9-solution": "Construction d'un système d'authentification à l'aide de Passport.js et optimisation de la requête de données relationnelles à l'aide de Mongoose populate.",
      "proj-9-role": "Développeur Full-Stack",
      
      // Project Badge Labels
      "badge-main": "Projet Principal",
      "badge-latest": "Projet Récent", 
      "badge-side": "Projet Secondaire",
      "badge-completed": "Terminé",
      "badge-in-progress": "En Cours"
  },
  jp: {
    "w-0-1": "ポートフォリオへようこそ。",
    "w-0-2": "言語を変更するには、国のアイコンをクリックしてください。",
    "w-0-3": "テーマを選択してください。",
    "w-1": "開始するには、お好みのテーマを選択してください",
    "w-2": "ライトモード",
    "w-3": "日中の使用に最適なクリーンで明るいインターフェース",
    "w-4": "ダークモード",
    "w-5": "目に優しく、暗い環境に最適なモード",
    "w-6": "この設定はアプリ内でいつでも変更できます",
    "w-7": "検出された言語:",
    "w-8": "閉じる",
    "h-1": "ポートフォリオ",
    "m-0": "こんにちは、",
    "m-0-0": "フロントエンド開発者のユ・ヒョヌです",
    "m-0-1": "お会いするまで ",
    "m-0-2": "✓ 完了",
    "m-0-3": "スワイプして開始",
    "m-1": "優れたデジタル体験を創造し、開発を設計することが大好きです。",
    "m-2": "私の作品を見る",
    "m-3": "履歴書をダウンロード",
    "m-4": "プロジェクト",
    "m-5": "受賞",
    "m-6": "満足したクライアント",
    "m-7": "年の経験",
    "m-8": "主なプロジェクト",
    "m-9": "技術とツール",
    "m-10": "一緒に働きましょう",
    "m-11": "プロジェクトのアイデアはありますか？ぜひお聞かせください。メッセージを送っていただければ、あなたのアイデアを実現する方法について話し合うことができます。",
    "DES-0": "ユ・ヒョヌ",
    "DES-5": "スタック",
    "c-0": "お問い合わせ",
    "c-1": "名前 *",
    "c-2": "メールアドレス *",
    "c-3": "電話番号（任意）",
    "c-4": "メッセージ *",
    "c-5": "送信",
    "c-6": "送信中...",
    "c-7": "メッセージは正常に送信されました！できるだけ早く返信いたします。",
    "c-8": "送信中にエラーが発生しました。もう一度お試しください。",
    "c-9": "名前を入力してください",
    "c-10": "メールアドレスを入力してください",
    "c-11": "電話番号を入力してください",
    "c-12": "メッセージを入力してください",
    "c-13": "任意",
    "c-14": "AWS Lambda Function実行中...",
    "scroll-to-top": "トップに戻る",
    "p-0": "すべて",
    "p-1": "メイン",
    "p-2": "サイド",
    "p-3": "完了",
    "p-4": "進行中",
    "p-5": "計画中",
    "p-6": "詳細を見る",
    "p-7": "GitHubコードを見る",
    "p-8": "ライブデモを見る",
    "p-9": "もっと見る",
    "p-10": "折りたたむ",
    "b-0": "最新のブログ投稿",
    "b-1": "続きを読む",
    "b-2": "詳細な内容についてはNotionショートカットをクリックしてください",
    "b-3": "Notionショートカット",
    "s-0": "言語とフレームワーク",
    "s-1": "ライブラリ",
    "s-2": "環境とデプロイ",
    "s-3": "デザインとコラボレーション",
    
    // Stack Filter Labels
    "stack-all": "すべて",
    "stack-language": "言語とフレームワーク",
    "stack-library": "ライブラリ",
    "stack-deployment": "環境とデプロイ",
    "stack-design": "デザインとコラボレーション",
    "proj-1-title": "The Clipoプロジェクト",
    "proj-1-desc": "React、Tailwind CSS、TypeScriptを使用したソーシャルメディアプラットフォームのポートフォリオ。",
    "proj-1-short": "個人ポートフォリオウェブサイト",
    "proj-1-overview": "ダーク/ライトモード、アクセストークン、リフレッシュトークンを備えた個人ポートフォリオ用のレスポンシブウェブサイト。友人とソーシャルメディアプラットフォームを実践的に開発しているかのように見せようとしました。",
    "proj-1-feature-1": "認証およびトークン管理システム",
    "proj-1-feature-2": "Reduxベースの多重ネストモーダルシステム",
    "proj-1-feature-3": "コアソーシャルメディア機能",
    "proj-1-feature-4": "UIコンポーネントおよびデザインシステム",
    "proj-1-feature-5": "データおよび状態管理",
    "proj-1-feature-6": "リアルタイム機能",
    "proj-1-challenge": "楽観的更新とデータ同期/バックエンドとの連携。",
    "proj-1-solution": "ネットワークエラー時に以前のクエリを取得して同期するためにReact-queryを使用。",
    "proj-1-role": "フロントエンド/プランナー",
    "proj-2-title": "サッカー動画の自動化",
    "proj-2-desc": "AWS LambdaとPythonを使用したMovie.pyによる動画自動化。",
    "proj-2-short": "",
    "proj-2-overview": "サッカーへの愛情から生まれた動画自動化システム。計画後、週に一度実行されるシステムの開発が始まりました。取得した試合スケジュールに基づいてAWS Lambdaをスケジュールし、Telegramボットを介して試合データを取得します。",
    "proj-2-feature-1": "Football APIからのデータ取得",
    "proj-2-feature-2": "Pythonでのデータ処理とTelegramボットの統合",
    "proj-2-feature-3": "AWS Lambdaのスケジューリングと実行",
    "proj-2-feature-4": "AWS S3へのファイルストレージ",
    "proj-2-feature-5": "Googleスプレッドシートの統合",
    "proj-2-feature-6": "Movie.pyによる動画自動化",
    "proj-2-feature-7": "YouTube APIの統合",
    "proj-2-challenge": "Movie.pyパッケージへの適応、AWS Step Functionのランタイムエラー処理。",
    "proj-2-solution": "Movie.pyの公式ドキュメントを参照して適応し、Step Functionのエラータイプを特定して処理。",
    "proj-2-role": "ソロ開発者",
    "proj-3-title": "カレンダーオート",
    "proj-3-desc": "自動化されたカレンダープラットフォーム",
    "proj-3-short": "Open AI APIを使用した自動カレンダースケジューリングシステム。",
    "proj-3-overview": "ユーザー認証、支払いシステム、管理者ダッシュボードを含む、完全に機能するeコマースプラットフォーム。",
    "proj-3-feature-1": "ユーザー認証と権限管理",
    "proj-3-feature-2": "製品の検索とフィルタリング",
    "proj-3-feature-3": "ショッピングカートとウィッシュリスト",
    "proj-3-feature-4": "Stripe支払いシステム",
    "proj-3-feature-5": "管理者ダッシュボード",
    "proj-3-feature-6": "リアルタイム在庫管理",
    "proj-3-challenge": "大量のトラフィック処理と支払いのセキュリティ。",
    "proj-3-solution": "RedisキャッシングとStripeのセキュアAPIを使用して安全な支払いシステムを構築。",
    "proj-3-role": "フロントエンド開発者",
    "proj-4-title": "Python Web求人スクレイパー",
    "proj-4-desc": "複数の求人サイトから求人情報を一度に検索・フィルタリングできる統合Webスクレイパー。",
    "proj-4-short": "Wanted、Saramin、RemoteOK、WeWorkRemotelyで求人情報を統合検索。",
    "proj-4-overview": "韓国および海外の求人サイトからリアルタイムで求人情報を収集し、統合検索を提供するWebアプリケーション。",
    "proj-4-feature-1": "4つの求人サイトの統合検索（Wanted、Saramin、RemoteOK、WeWorkRemotely）",
    "proj-4-feature-2": "サイトごとの選択的検索機能",
    "proj-4-feature-3": "地域別フィルタリング（ソウル、京畿、仁川など）",
    "proj-4-feature-4": "リアルタイム求人情報収集",
    "proj-4-feature-5": "CSVファイルダウンロード機能",
    "proj-4-feature-6": "モバイルレスポンシブデザイン",
    "proj-4-feature-7": "動的Webスクレイピング（Selenium）",
    "proj-4-feature-8": "APIベースのデータ収集（Wanted、RemoteOK）",
    "proj-4-feature-9": "サイトごとの統計とフィルタリング",
    "proj-4-feature-10": "検索結果のリアルタイム更新",
    "proj-4-challenge": "様々なサイトのアクセス制限と動的コンテンツの処理、安定したデータ収集。",
    "proj-4-solution": "Seleniumとrequestsのハイブリッドアプローチ、エラーハンドリングとフォールバックメカニズムの実装。",
    "proj-4-role": "フルスタック開発者",
    "proj-5-title": "ランダムコード練習アプリ",
    "proj-5-desc": "音楽練習のためのモダンで使いやすいランダムコードジェネレーター。",
    "proj-5-short": "Webベースの音楽コード練習アプリ。",
    "proj-5-overview": "ミュージシャンのためのランダムコード練習アプリで、様々なコードタイプとテンポ設定を通じて体系的な音楽練習を提供します。Web Speech APIによる音声ガイダンスとリアルタイムテンポ調整機能を備えています。",
    "proj-5-feature-1": "ランダムコード生成と練習",
    "proj-5-feature-2": "17音のサポート（C、Db、D、Eb、E、F、Gb、G、Ab、A、Bb、B、C#、D#、F#、G#、A#）",
    "proj-5-feature-3": "様々なコードタイプ（Maj7、min7、7、sus4、add9など50種類以上）",
    "proj-5-feature-4": "リアルタイムテンポ調整（1-220 BPM）",
    "proj-5-feature-5": "ビートの視覚化（4拍子ドットアニメーション）",
    "proj-5-feature-6": "音声ガイダンスシステム（TTS）",
    "proj-5-feature-7": "カスタムコードの追加/削除",
    "proj-5-feature-8": "設定の保存（ローカルストレージ）",
    "proj-5-feature-9": "レスポンシブデザイン",
    "proj-5-feature-10": "A/Bフォームパターンの選択",
    "proj-5-challenge": "複雑なページナビゲーションとリアルタイムテンポ変更時のビート同期の維持。",
    "proj-5-solution": "3コンポーネント構造（タイトル/メイン/設定）とインターバルベースのビートアニメーションによる安定した状態管理の実装。",
    "proj-5-role": "フルスタック開発者",
    "proj-6-title": "The Area - クリエイティブプラットフォーム",
    "proj-6-desc": "音楽、ビジュアル、クリエイターのための総合クリエイティブプラットフォーム。",
    "proj-6-short": "クリエイティブプラットフォーム",
    "proj-6-overview": "音楽、ビジュアルアート、クリエイターのための総合クリエイティブプラットフォーム。",
    "proj-6-feature-1": "ビデオ背景とロゴアニメーション",
    "proj-6-feature-2": "ミュージックビデオプレーヤー",
    "proj-6-feature-3": "クリエイタープロフィールギャラリー",
    "proj-6-feature-4": "MVギャラリーシステム",
    "proj-6-feature-5": "レスポンシブデザイン",
    "proj-6-feature-6": "ページルーティングシステム",
    "proj-6-challenge": "複雑なアニメーションとビデオ処理、レスポンシブデザインの実装。",
    "proj-6-solution": "CSSアニメーションとReactの状態管理による動的UIの実装。",
    "proj-6-role": "フルスタック開発者",
    "proj-7-title": "サッカーアプリウェブサイト",
    "proj-7-desc": "HTML、CSS、JavaScriptで作成されたサッカーテーマのカカオトーククローンモバイルウェブサイト。",
    "proj-7-short": "サッカーテーマのチャットアプリクローン。",
    "proj-7-overview": "カカオトークのUI/UXを模倣したウェブサイトで、サッカーテーマのチャットアプリケーションです。モバイルファーストのアプローチでレスポンシブウェブデザインを実装しました。",
    "proj-7-feature-1": "リアルタイム時計表示",
    "proj-7-feature-2": "モバイルレスポンシブデザイン",
    "proj-7-feature-3": "サッカー試合日程とライブストリーミングセクション",
    "proj-7-feature-4": "チャットルームリストと個別チャットルーム",
    "proj-7-feature-5": "プロフィールページ（サッカー選手情報を含む）",
    "proj-7-feature-6": "コミュニティと検索機能",
    "proj-7-feature-7": "Font Awesomeアイコンの活用",
    "proj-7-feature-8": "CSSアニメーション効果",
    "proj-7-feature-9": "モバイル画面サイズ制限機能",
    "proj-7-challenge": "モバイルファーストデザインとカカオトークの複雑なUI構造をWebで実装すること。",
    "proj-7-solution": "CSS GridとFlexboxによるレイアウト構成、JavaScriptによるリアルタイム機能の実装、モバイル画面サイズ検出機能の追加。",
    "proj-7-role": "フルスタックWeb開発者",
    "proj-8-title": "Momentumダッシュボード",
    "proj-8-desc": "個人の生産性を向上させるためのオールインワンダッシュボードWebアプリケーション。",
    "proj-8-short": "Webベースの個人用ダッシュボード。",
    "proj-8-overview": "個人の生産性を向上させるためのオールインワンダッシュボードで、リアルタイム時計、天気情報、ToDo管理、音楽プレーヤー、名言表示、Google検索を統合したモダンなWebアプリケーションです。パーソナライズとレスポンシブデザインにより最適なユーザー体験を提供します。",
    "proj-8-feature-1": "リアルタイムデジタル時計と日付表示",
    "proj-8-feature-2": "地理位置情報に基づく現在地の天気情報",
    "proj-8-feature-3": "OpenWeather API連携（気温、湿度、体感温度など）",
    "proj-8-feature-4": "ToDoリスト管理（追加、完了、削除）",
    "proj-8-feature-5": "ローカルストレージによるデータ永続化",
    "proj-8-feature-6": "YouTube APIベースの音楽プレーヤー",
    "proj-8-feature-7": "プレイリスト管理（再生、一時停止、前/次へ）",
    "proj-8-feature-8": "ランダム名言表示システム",
    "proj-8-feature-9": "Google検索統合",
    "proj-8-feature-10": "時間帯に合わせたパーソナライズされた挨拶",
    "proj-8-feature-11": "時間帯に応じた背景画像の自動変更",
    "proj-8-feature-12": "ユーザー名設定とログアウト機能",
    "proj-8-feature-13": "レスポンシブデザインとアニメーション効果",
    "proj-8-challenge": "複数のAPI連携とローカルストレージによる状態管理、リアルタイムデータ同期。",
    "proj-8-solution": "モジュール化されたJavaScript構造とイベント駆動プログラミングによる安定した状態管理の実装。",
    "proj-8-role": "フルスタック開発者",
    "proj-9-title": "キャンプ場管理システム",
    "proj-9-desc": "キャンプ場情報の登録、照会、修正、削除、およびレビューシステムを提供するWebアプリケーション。",
    "proj-9-short": "統合キャンプ場管理プラットフォーム。",
    "proj-9-overview": "キャンプ場情報を登録・管理できるWebアプリケーションです。ユーザー認証、キャンプ場のCRUD機能、レビューシステムを含みます。",
    "proj-9-feature-1": "ユーザー登録/ログイン/ログアウト",
    "proj-9-feature-2": "キャンプ場情報登録（タイトル、場所、価格、説明、写真）",
    "proj-9-feature-3": "キャンプ場リストの照会と詳細表示",
    "proj-9-feature-4": "キャンプ場情報の修正と削除",
    "proj-9-feature-5": "作成者権限管理（自分の投稿のみ修正/削除可能）",
    "proj-9-feature-6": "レビューシステム（評価とテキストレビュー）",
    "proj-9-feature-7": "レスポンシブウェブデザイン（Bootstrap 5）",
    "proj-9-feature-8": "フラッシュメッセージによるユーザーフィードバック",
    "proj-9-feature-9": "セッションベースの認証システム",
    "proj-9-challenge": "ユーザー認証システムと権限管理の実装、MongoDBでのリレーショナルデータ処理。",
    "proj-9-solution": "Passport.jsによる認証システムの構築とMongoose populateによるリレーショナルデータクエリの最適化。",
    "proj-9-role": "フルスタック開発者",
    
    // Project Badge Labels
    "badge-main": "メインプロジェクト",
    "badge-latest": "最新プロジェクト", 
    "badge-side": "サイドプロジェクト",
    "badge-completed": "完了",
    "badge-in-progress": "制作中"
  },
  cn: {
    "w-0-1": "欢迎来到作品集。",
    "w-0-2": "点击国家图标以更改语言。",
    "w-0-3": "请选择一个主题。",
    "w-1": "选择您喜欢的主题以开始",
    "w-2": "浅色模式",
    "w-3": "一个干净明亮的界面，非常适合白天使用",
    "w-4": "深色模式",
    "w-5": "一种对眼睛友好的模式，非常适合黑暗环境",
    "w-6": "您可以随时在应用程序中更改此设置",
    "w-7": "检测到的语言：",
    "w-8": "关闭",
    "h-1": "作品集",
    "m-0": "你好，",
    "m-0-0": "我是前端开发人员 Yu Hyunwu",
    "m-0-1": "直到我们见面 ",
    "m-0-2": "✓ 完成",
    "m-0-3": "滑动开始",
    "m-1": "我喜欢创造卓越的数字体验和设计开发。",
    "m-2": "查看我的作品",
    "m-3": "下载简历",
    "m-4": "项目",
    "m-5": "奖项",
    "m-6": "满意的客户",
    "m-7": "年经验",
    "m-8": "主要项目",
    "m-9": "技术与工具",
    "m-10": "让我们一起工作",
    "m-11": "您有项目想法吗？我很想听听。给我发个消息，我们可以讨论如何将您的想法变为现实。",
    "DES-0": "Yu Hyunwu",
    "DES-5": "技术栈",
    "c-0": "联系",
    "c-1": "姓名 *",
    "c-2": "电子邮件 *",
    "c-3": "电话号码（可选）",
    "c-4": "信息 *",
    "c-5": "发送",
    "c-6": "发送中...",
    "c-7": "您的信息已成功发送！我会尽快给您回复。",
    "c-8": "发送时发生错误。请再试一次。",
    "c-9": "请输入您的姓名",
    "c-10": "请输入您的电子邮件",
    "c-11": "请输入您的电话号码",
    "c-12": "请输入您的信息",
    "c-13": "可选",
    "c-14": "AWS Lambda Function执行中...",
    "scroll-to-top": "回到顶部",
    "p-0": "全部",
    "p-1": "主要",
    "p-2": "次要",
    "p-3": "已完成",
    "p-4": "进行中",
    "p-5": "计划中",
    "p-6": "了解更多",
    "p-7": "查看 GitHub 代码",
    "p-8": "查看现场演示",
    "p-9": "查看更多",
    "p-10": "折叠",
    "b-0": "最新博客文章",
    "b-1": "阅读更多",
    "b-2": "请点击Notion快捷方式查看详细内容",
    "b-3": "Notion快捷方式",
    "s-0": "语言与框架",
    "s-1": "库",
    "s-2": "环境与部署",
    "s-3": "设计与协作",
    
    // Stack Filter Labels
    "stack-all": "全部",
    "stack-language": "语言与框架",
    "stack-library": "库",
    "stack-deployment": "环境与部署",
    "stack-design": "设计与协作",
    "proj-1-title": "Clipo 项目",
    "proj-1-desc": "使用 React、Tailwind CSS 和 TypeScript 的社交媒体平台作品集。",
    "proj-1-short": "个人作品集网站",
    "proj-1-overview": "一个用于个人作品集的响应式网站，具有深色/浅色模式、访问令牌和刷新令牌。我试图让它看起来像我和一个朋友正在为实践开发一个社交媒体平台。",
    "proj-1-feature-1": "身份验证和令牌管理系统",
    "proj-1-feature-2": "基于 Redux 的多层嵌套模态系统",
    "proj-1-feature-3": "核心社交媒体功能",
    "proj-1-feature-4": "UI 组件和设计系统",
    "proj-1-feature-5": "数据和状态管理",
    "proj-1-feature-6": "实时功能",
    "proj-1-challenge": "乐观更新和数据同步/与后端的协作。",
    "proj-1-solution": "使用 React-query 在网络错误时通过获取先前的查询进行同步。",
    "proj-1-role": "前端/策划",
    "proj-2-title": "足球视频自动化",
    "proj-2-desc": "使用 AWS Lambda 和 Python 的 Movie.py 实现视频自动化。",
    "proj-2-short": "",
    "proj-2-overview": "一个源于我对足球的热爱的视频自动化系统。在规划之后，开发开始于一个每周运行一次的系统。它根据获取的比赛时间表安排 AWS Lambda，并通过 Telegram 机器人获取比赛数据。",
    "proj-2-feature-1": "从 Football API 获取数据",
    "proj-2-feature-2": "Python 数据处理和 Telegram 机器人集成",
    "proj-2-feature-3": "AWS Lambda 调度和执行",
    "proj-2-feature-4": "AWS S3 文件存储",
    "proj-2-feature-5": "Google Spreadsheet 集成",
    "proj-2-feature-6": "使用 Movie.py 进行视频自动化",
    "proj-2-feature-7": "YouTube API 集成",
    "proj-2-challenge": "适应 Movie.py 包，AWS Step Function 运行时错误处理。",
    "proj-2-solution": "通过参考 Movie.py 官方文档进行适应，识别和处理 Step Function 中的错误类型。",
    "proj-2-role": "独立开发者",
    "proj-3-title": "日历自动化",
    "proj-3-desc": "自动化日历平台",
    "proj-3-short": "使用 Open AI API 的自动日历调度系统。",
    "proj-3-overview": "一个功能齐全的电子商务平台，包括用户身份验证、支付系统和管理仪表板。",
    "proj-3-feature-1": "用户身份验证和权限管理",
    "proj-3-feature-2": "产品搜索和筛选",
    "proj-3-feature-3": "购物车和愿望清单",
    "proj-3-feature-4": "Stripe 支付系统",
    "proj-3-feature-5": "管理仪表板",
    "proj-3-feature-6": "实时库存管理",
    "proj-3-challenge": "处理高流量和支付安全。",
    "proj-3-solution": "使用 Redis 缓存和 Stripe 的安全 API 构建安全的支付系统。",
    "proj-3-role": "前端开发人员",
    "proj-4-title": "Python Web 职位抓取器",
    "proj-4-desc": "一个集成的 Web 抓取器，可同时在多个招聘网站上搜索和筛选职位发布。",
    "proj-4-short": "在 Wanted、Saramin、RemoteOK 和 WeWorkRemotely 上集成搜索职位发布。",
    "proj-4-overview": "一个 Web 应用程序，可从韩国和国际招聘网站实时收集职位发布并提供集成搜索。",
    "proj-4-feature-1": "在 4 个招聘网站上集成搜索（Wanted、Saramin、RemoteOK、WeWorkRemotely）",
    "proj-4-feature-2": "每个网站的选择性搜索功能",
    "proj-4-feature-3": "按地区筛选（首尔、京畿、仁川等）",
    "proj-4-feature-4": "实时收集职位发布",
    "proj-4-feature-5": "CSV 文件下载功能",
    "proj-4-feature-6": "移动响应式设计",
    "proj-4-feature-7": "动态 Web 抓取（Selenium）",
    "proj-4-feature-8": "基于 API 的数据收集（Wanted、RemoteOK）",
    "proj-4-feature-9": "网站统计和筛选",
    "proj-4-feature-10": "实时更新搜索结果",
    "proj-4-challenge": "处理各种网站的访问限制和动态内容，稳定的数据收集。",
    "proj-4-solution": "采用 Selenium 和 requests 的混合方法，错误处理和实现回退机制。",
    "proj-4-role": "全栈开发人员",
    "proj-5-title": "随机和弦练习应用程序",
    "proj-5-desc": "一个现代且用户友好的随机和弦生成器，用于音乐练习。",
    "proj-5-short": "基于 Web 的音乐和弦练习应用程序。",
    "proj-5-overview": "一个为音乐家设计的随机和弦练习应用程序，通过各种和弦类型和速度设置提供系统的音乐练习。包括使用 Web Speech API 的语音指导和实时速度调整。",
    "proj-5-feature-1": "随机和弦生成和练习",
    "proj-5-feature-2": "支持 17 个音符（C、Db、D、Eb、E、F、Gb、G、Ab、A、Bb、B、C#、D#、F#、G#、A#）",
    "proj-5-feature-3": "各种和弦类型（Maj7、min7、7、sus4、add9 等 50 多种类型）",
    "proj-5-feature-4": "实时速度调整（1-220 BPM）",
    "proj-5-feature-5": "节拍可视化（4 拍点动画）",
    "proj-5-feature-6": "语音指导系统（TTS）",
    "proj-5-feature-7": "添加/删除自定义和弦",
    "proj-5-feature-8": "保存设置（本地存储）",
    "proj-5-feature-9": "响应式设计",
    "proj-5-feature-10": "A/B 表单模式选择",
    "proj-5-challenge": "复杂的页面导航和在实时速度变化期间保持节拍同步。",
    "proj-5-solution": "使用 3 组件结构（标题/主要/设置）和基于间隔的节拍动画实现稳定的状态管理。",
    "proj-5-role": "全栈开发人员",
    "proj-6-title": "The Area - 创意平台",
    "proj-6-desc": "一个面向音乐、视觉和创作者的综合创意平台。",
    "proj-6-short": "创意平台",
    "proj-6-overview": "一个面向音乐、视觉艺术和创作者的综合创意平台。",
    "proj-6-feature-1": "视频背景和徽标动画",
    "proj-6-feature-2": "音乐视频播放器",
    "proj-6-feature-3": "创作者个人资料库",
    "proj-6-feature-4": "MV 画廊系统",
    "proj-6-feature-5": "响应式设计",
    "proj-6-feature-6": "页面路由系统",
    "proj-6-challenge": "复杂的动画和视频处理，实现响应式设计。",
    "proj-6-solution": "使用 CSS 动画和 React 状态管理实现动态 UI。",
    "proj-6-role": "全栈开发人员",
    "proj-7-title": "足球应用程序网站",
    "proj-7-desc": "一个使用 HTML、CSS 和 JavaScript 创建的以足球为主题的 KakaoTalk 克隆移动网站。",
    "proj-7-short": "足球主题聊天应用程序克隆。",
    "proj-7-overview": "一个模仿 KakaoTalk UI/UX 的网站，一个以足球为主题的聊天应用程序。采用移动优先的方法实现响应式网页设计。",
    "proj-7-feature-1": "实时时钟显示",
    "proj-7-feature-2": "移动响应式设计",
    "proj-7-feature-3": "足球比赛时间表和直播部分",
    "proj-7-feature-4": "聊天室列表和个人聊天室",
    "proj-7-feature-5": "个人资料页面（包括足球运动员信息）",
    "proj-7-feature-6": "社区和搜索功能",
    "proj-7-feature-7": "使用 Font Awesome 图标",
    "proj-7-feature-8": "CSS 动画效果",
    "proj-7-feature-9": "移动屏幕尺寸限制功能",
    "proj-7-challenge": "移动优先设计和在 Web 上实现 KakaoTalk 复杂的 UI 结构。",
    "proj-7-solution": "使用 CSS Grid 和 Flexbox 的布局组合，使用 JavaScript 实现实时功能，添加移动屏幕尺寸检测功能。",
    "proj-7-role": "全栈 Web 开发人员",
    "proj-8-title": "Momentum 仪表板",
    "proj-8-desc": "一个用于提高个人生产力的一体化仪表板 Web 应用程序。",
    "proj-8-short": "基于 Web 的个人仪表板。",
    "proj-8-overview": "一个用于提高个人生产力的一体化仪表板，一个现代 Web 应用程序，集成了实时时钟、天气信息、待办事项管理、音乐播放器、报价显示和 Google 搜索。通过个性化和响应式设计提供最佳的用户体验。",
    "proj-8-feature-1": "实时数字时钟和日期显示",
    "proj-8-feature-2": "基于地理位置的当前位置天气信息",
    "proj-8-feature-3": "OpenWeather API 集成（温度、湿度、体感温度等）",
    "proj-8-feature-4": "待办事项列表管理（添加、完成、删除）",
    "proj-8-feature-5": "使用本地存储持久化数据",
    "proj-8-feature-6": "基于 YouTube API 的音乐播放器",
    "proj-8-feature-7": "播放列表管理（播放、暂停、上一首/下一首）",
    "proj-8-feature-8": "随机报价显示系统",
    "proj-8-feature-9": "Google 搜索集成",
    "proj-8-feature-10": "基于时间的个性化问候",
    "proj-8-feature-11": "根据时间自动更换背景图片",
    "proj-8-feature-12": "用户名设置和注销功能",
    "proj-8-feature-13": "响应式设计和动画效果",
    "proj-8-challenge": "多 API 集成和使用本地存储的状态管理，实时数据同步。",
    "proj-8-solution": "使用模块化 JavaScript 结构和事件驱动编程实现稳定的状态管理。",
    "proj-8-role": "全栈开发人员",
    "proj-9-title": "露营地管理系统",
    "proj-9-desc": "一个用于注册、查看、修改和删除露营地信息以及评论系统的 Web 应用程序。",
    "proj-9-short": "集成的露营地管理平台。",
    "proj-9-overview": "一个用于注册和管理露营地信息的 Web 应用程序。包括用户身份验证、露营地的 CRUD 功能和评论系统。",
    "proj-9-feature-1": "用户注册/登录/注销",
    "proj-9-feature-2": "露营地信息注册（标题、位置、价格、描述、照片）",
    "proj-9-feature-3": "查看露营地列表和详细信息",
    "proj-9-feature-4": "修改和删除露营地信息",
    "proj-9-feature-5": "作者权限管理（只能修改/删除自己的帖子）",
    "proj-9-feature-6": "评论系统（评级和文本评论）",
    "proj-9-feature-7": "响应式网页设计（Bootstrap 5）",
    "proj-9-feature-8": "通过闪存消息提供用户反馈",
    "proj-9-feature-9": "基于会话的身份验证系统",
    "proj-9-challenge": "实现用户身份验证系统和权限管理，处理 MongoDB 中的关系数据。",
    "proj-9-solution": "使用 Passport.js 构建身份验证系统，并使用 Mongoose populate 优化关系数据查询。",
    "proj-9-role": "全栈开发人员",
    
    // Project Badge Labels
    "badge-main": "主要项目",
    "badge-latest": "最新项目", 
    "badge-side": "副项目",
    "badge-completed": "已完成",
    "badge-in-progress": "进行中"
  },
  de: {
    "w-0-1": "Willkommen im Portfolio.",
    "w-0-2": "Klicken Sie auf das Ländersymbol, um die Sprache zu ändern.",
    "w-0-3": "Bitte wählen Sie ein Thema.",
    "w-1": "Wählen Sie Ihr bevorzugtes Thema, um zu beginnen",
    "w-2": "Light-Modus",
    "w-3": "Eine saubere, helle Benutzeroberfläche, perfekt für den Tag",
    "w-4": "Dark-Modus",
    "w-5": "Ein augenschonender Modus, perfekt für dunkle Umgebungen",
    "w-6": "Sie können diese Einstellung jederzeit in der App ändern",
    "w-7": "Erkannte Sprache:",
    "w-8": "Schließen",
    "h-1": "Portfolio",
    "m-0": "Hallo,",
    "m-0-0": "ich bin Hyunwu Yu, ein Frontend-Entwickler",
    "m-0-1": "Bis zum Kennenlernen ",
    "m-0-2": "✓ Abgeschlossen",
    "m-0-3": "Wischen, um zu starten",
    "m-1": "Ich liebe es, herausragende digitale Erlebnisse zu schaffen und Entwicklungen zu gestalten.",
    "m-2": "Meine Arbeit ansehen",
    "m-3": "Lebenslauf herunterladen",
    "m-4": "Projekte",
    "m-5": "Auszeichnungen",
    "m-6": "Zufriedene Kunden",
    "m-7": "Jahre Erfahrung",
    "m-8": "Hauptprojekte",
    "m-9": "Technologien & Werkzeuge",
    "m-10": "Lassen Sie uns zusammenarbeiten",
    "m-11": "Haben Sie eine Projektidee? Ich würde sie gerne hören. Senden Sie mir eine Nachricht und wir können besprechen, wie wir Ihre Idee verwirklichen können.",
    "DES-0": "Hyunwu Yu",
    "DES-5": "Stack",
    "c-0": "Kontakt",
    "c-1": "Name *",
    "c-2": "E-Mail *",
    "c-3": "Telefonnummer (optional)",
    "c-4": "Nachricht *",
    "c-5": "Senden",
    "c-6": "Senden...",
    "c-7": "Ihre Nachricht wurde erfolgreich gesendet! Ich werde mich so schnell wie möglich bei Ihnen melden.",
    "c-8": "Beim Senden ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    "c-9": "Bitte geben Sie Ihren Namen ein",
    "c-10": "Bitte geben Sie Ihre E-Mail-Adresse ein",
    "c-11": "Bitte geben Sie Ihre Telefonnummer ein",
    "c-12": "Bitte geben Sie eine Nachricht ein",
    "c-13": "Optional",
    "c-14": "AWS Lambda Function wird ausgeführt...",
    "scroll-to-top": "Nach oben",
    "p-0": "Alle",
    "p-1": "Haupt",
    "p-2": "Neben",
    "p-3": "Abgeschlossen",
    "p-4": "In Arbeit",
    "p-5": "Geplant",
    "p-6": "Mehr erfahren",
    "p-7": "GitHub-Code ansehen",
    "p-8": "Live-Demo ansehen",
    "p-9": "Mehr anzeigen",
    "p-10": "Einklappen",
    "b-0": "Neueste Blog-Beiträge",
    "b-1": "Weiterlesen",
    "b-2": "Klicken Sie auf den Notion-Verknüpfung für detaillierte Inhalte",
    "b-3": "Notion-Verknüpfung",
    "s-0": "Sprachen & Frameworks",
    "s-1": "Bibliotheken",
    "s-2": "Umgebung & Bereitstellung",
    "s-3": "Design & Kollaboration",
    
    // Stack Filter Labels
    "stack-all": "Alle",
    "stack-language": "Sprachen & Frameworks",
    "stack-library": "Bibliotheken",
    "stack-deployment": "Umgebung & Bereitstellung",
    "stack-design": "Design & Kollaboration",
    "proj-1-title": "Das Clipo-Projekt",
    "proj-1-desc": "Ein Social-Media-Plattform-Portfolio mit React, Tailwind CSS und TypeScript.",
    "proj-1-short": "Persönliche Portfolio-Website",
    "proj-1-overview": "Eine responsive Website für ein persönliches Portfolio mit Dark/Light-Modus, Access Token und Refresh Token. Ich habe versucht, es so zu gestalten, als ob ich mit einem Freund eine Social-Media-Plattform für die Praxis entwickle.",
    "proj-1-feature-1": "Authentifizierungs- und Token-Management-System",
    "proj-1-feature-2": "Auf Redux basierendes, mehrfach verschachteltes Modal-System",
    "proj-1-feature-3": "Kernfunktionen für soziale Medien",
    "proj-1-feature-4": "UI-Komponenten und Designsystem",
    "proj-1-feature-5": "Daten- und Zustandsverwaltung",
    "proj-1-feature-6": "Echtzeit-Funktionen",
    "proj-1-challenge": "Optimistische Updates und Datensynchronisation / Zusammenarbeit mit dem Backend.",
    "proj-1-solution": "Verwendung von React-Query zur Synchronisation durch Abrufen früherer Abfragen bei Netzwerkfehlern.",
    "proj-1-role": "Frontend / Planer",
    "proj-2-title": "Automatisierung von Fußballvideos",
    "proj-2-desc": "Videoautomatisierung mit Movie.py unter Verwendung von AWS Lambda und Python.",
    "proj-2-short": "",
    "proj-2-overview": "Ein aus meiner Liebe zum Fußball entstandenes Videoautomatisierungssystem. Nach der Planung begann die Entwicklung eines einmal wöchentlich laufenden Systems. Es plant AWS Lambda basierend auf abgerufenen Spielplänen und holt Spieldaten über einen Telegram-Bot.",
    "proj-2-feature-1": "Abrufen von Daten von der Football API",
    "proj-2-feature-2": "Datenverarbeitung in Python und Telegram-Bot-Integration",
    "proj-2-feature-3": "Planung und Ausführung von AWS Lambda",
    "proj-2-feature-4": "Dateispeicherung in AWS S3",
    "proj-2-feature-5": "Google Spreadsheet-Integration",
    "proj-2-feature-6": "Videoautomatisierung mit Movie.py",
    "proj-2-feature-7": "YouTube-API-Integration",
    "proj-2-challenge": "Anpassung an das Movie.py-Paket, Fehlerbehandlung bei der Laufzeit von AWS Step Function.",
    "proj-2-solution": "Anpassung durch Verweis auf die offizielle Dokumentation von Movie.py, Identifizierung und Behandlung von Fehlertypen in Step Function.",
    "proj-2-role": "Einzelentwickler",
    "proj-3-title": "Kalender-Auto",
    "proj-3-desc": "Automatisierte Kalenderplattform",
    "proj-3-short": "Automatisches Kalenderplanungssystem mit der Open AI API.",
    "proj-3-overview": "Eine voll funktionsfähige E-Commerce-Plattform mit Benutzerauthentifizierung, Zahlungssystem und Admin-Dashboard.",
    "proj-3-feature-1": "Benutzerauthentifizierung und Berechtigungsverwaltung",
    "proj-3-feature-2": "Produktsuche und -filterung",
    "proj-3-feature-3": "Warenkorb und Wunschliste",
    "proj-3-feature-4": "Stripe-Zahlungssystem",
    "proj-3-feature-5": "Admin-Dashboard",
    "proj-3-feature-6": "Echtzeit-Bestandsverwaltung",
    "proj-3-challenge": "Verarbeitung von hohem Traffic und Zahlungssicherheit.",
    "proj-3-solution": "Aufbau eines sicheren Zahlungssystems mit Redis-Caching und der sicheren API von Stripe.",
    "proj-3-role": "Frontend-Entwickler",
    "proj-4-title": "Python Web Job Scraper",
    "proj-4-desc": "Ein integrierter Web-Scraper zum gleichzeitigen Suchen und Filtern von Stellenangeboten auf mehreren Jobportalen.",
    "proj-4-short": "Integrierte Suche nach Stellenangeboten auf Wanted, Saramin, RemoteOK und WeWorkRemotely.",
    "proj-4-overview": "Eine Webanwendung, die Stellenangebote von koreanischen und internationalen Jobportalen in Echtzeit sammelt und eine integrierte Suche ermöglicht.",
    "proj-4-feature-1": "Integrierte Suche auf 4 Jobportalen (Wanted, Saramin, RemoteOK, WeWorkRemotely)",
    "proj-4-feature-2": "Selektive Suchfunktion pro Seite",
    "proj-4-feature-3": "Regionale Filterung (Seoul, Gyeonggi, Incheon usw.)",
    "proj-4-feature-4": "Sammlung von Stellenangeboten in Echtzeit",
    "proj-4-feature-5": "CSV-Datei-Download-Funktion",
    "proj-4-feature-6": "Mobiles responsives Design",
    "proj-4-feature-7": "Dynamisches Web-Scraping (Selenium)",
    "proj-4-feature-8": "API-basierte Datensammlung (Wanted, RemoteOK)",
    "proj-4-feature-9": "Seitenstatistiken und Filterung",
    "proj-4-feature-10": "Echtzeit-Aktualisierung der Suchergebnisse",
    "proj-4-challenge": "Umgang mit Zugriffsbeschränkungen auf verschiedenen Websites und dynamischen Inhalten, stabile Datensammlung.",
    "proj-4-solution": "Ein hybrider Ansatz mit Selenium und Requests, Fehlerbehandlung und Implementierung von Fallback-Mechanismen.",
    "proj-4-role": "Full-Stack-Entwickler",
    "proj-5-title": "Zufalls-Akkord-Übungs-App",
    "proj-5-desc": "Ein moderner und benutzerfreundlicher Zufalls-Akkord-Generator für das Musiküben.",
    "proj-5-short": "Webbasierte Musik-Akkord-Übungs-App.",
    "proj-5-overview": "Eine Zufalls-Akkord-Übungs-App für Musiker, die systematisches Üben durch verschiedene Akkordtypen und Tempoeinstellungen ermöglicht. Beinhaltet Sprachführung mit der Web Speech API und Echtzeit-Tempoanpassung.",
    "proj-5-feature-1": "Zufällige Akkorderzeugung und Übung",
    "proj-5-feature-2": "Unterstützung für 17 Noten (C, Db, D, Eb, E, F, Gb, G, Ab, A, Bb, B, C#, D#, F#, G#, A#)",
    "proj-5-feature-3": "Verschiedene Akkordtypen (Maj7, min7, 7, sus4, add9 usw. 50+ Typen)",
    "proj-5-feature-4": "Echtzeit-Tempoanpassung (1-220 BPM)",
    "proj-5-feature-5": "Taktvisualisierung (4-Takt-Punkt-Animation)",
    "proj-5-feature-6": "Sprachführungssystem (TTS)",
    "proj-5-feature-7": "Benutzerdefinierte Akkorde hinzufügen/entfernen",
    "proj-5-feature-8": "Einstellungen speichern (Local Storage)",
    "proj-5-feature-9": "Responsives Design",
    "proj-5-feature-10": "Auswahl des A/B-Formularmusters",
    "proj-5-challenge": "Komplexe Seitennavigation und Aufrechterhaltung der Taktsynchronisation bei Echtzeit-Tempoänderungen.",
    "proj-5-solution": "Stabile Zustandsverwaltung mit einer 3-Komponenten-Struktur (Titel/Haupt/Einstellungen) und intervallbasierter Taktanimation.",
    "proj-5-role": "Full-Stack-Entwickler",
    "proj-6-title": "The Area - Kreativplattform",
    "proj-6-desc": "Eine umfassende Kreativplattform für Musik, Visuals und Kreative.",
    "proj-6-short": "Kreativplattform",
    "proj-6-overview": "Eine umfassende Kreativplattform für Musik, visuelle Kunst und Kreative.",
    "proj-6-feature-1": "Videohintergrund und Logo-Animation",
    "proj-6-feature-2": "Musikvideo-Player",
    "proj-6-feature-3": "Kreativen-Profil-Galerie",
    "proj-6-feature-4": "MV-Galerie-System",
    "proj-6-feature-5": "Responsives Design",
    "proj-6-feature-6": "Seiten-Routing-System",
    "proj-6-challenge": "Komplexe Animationen und Videoverarbeitung, Implementierung eines responsiven Designs.",
    "proj-6-solution": "Dynamische UI-Implementierung mit CSS-Animationen und React-Zustandsverwaltung.",
    "proj-6-role": "Full-Stack-Entwickler",
    "proj-7-title": "Fußball-Anwendungs-Website",
    "proj-7-desc": "Eine mobile Klon-Website einer KakaoTalk-App mit Fußball-Thema, erstellt mit HTML, CSS und JavaScript.",
    "proj-7-short": "Fußball-Themen-Chat-App-Klon.",
    "proj-7-overview": "Eine Website, die die UI/UX von KakaoTalk nachahmt, eine Chat-Anwendung mit Fußball-Thema. Implementiert ein responsives Webdesign mit einem Mobile-First-Ansatz.",
    "proj-7-feature-1": "Echtzeit-Uhranzeige",
    "proj-7-feature-2": "Mobiles responsives Design",
    "proj-7-feature-3": "Fußballspielplan und Live-Streaming-Bereich",
    "proj-7-feature-4": "Chatraumliste und einzelne Chaträume",
    "proj-7-feature-5": "Profilseite (einschließlich Informationen zu Fußballspielern)",
    "proj-7-feature-6": "Community- und Suchfunktionen",
    "proj-7-feature-7": "Verwendung von Font Awesome-Symbolen",
    "proj-7-feature-8": "CSS-Animationseffekte",
    "proj-7-feature-9": "Funktion zur Begrenzung der mobilen Bildschirmgröße",
    "proj-7-challenge": "Mobile-First-Design und Implementierung der komplexen UI-Struktur von KakaoTalk im Web.",
    "proj-7-solution": "Layout-Komposition mit CSS Grid und Flexbox, Implementierung von Echtzeit-Funktionen mit JavaScript, Hinzufügen einer Funktion zur Erkennung der mobilen Bildschirmgröße.",
    "proj-7-role": "Full-Stack-Webentwickler",
    "proj-8-title": "Momentum Dashboard",
    "proj-8-desc": "Ein All-in-One-Dashboard-Webanwendung zur Steigerung der persönlichen Produktivität.",
    "proj-8-short": "Webbasiertes persönliches Dashboard.",
    "proj-8-overview": "Ein All-in-One-Dashboard zur Steigerung der persönlichen Produktivität, eine moderne Webanwendung, die Echtzeituhr, Wetterinformationen, Aufgabenverwaltung, Musik-Player, Zitat-Anzeige und Google-Suche integriert. Bietet eine optimale Benutzererfahrung durch Personalisierung und responsives Design.",
    "proj-8-feature-1": "Echtzeit-Digitaluhr und Datumsanzeige",
    "proj-8-feature-2": "Geolocation-basierte aktuelle Standort-Wetterinformationen",
    "proj-8-feature-3": "OpenWeather-API-Integration (Temperatur, Luftfeuchtigkeit, gefühlte Temperatur usw.)",
    "proj-8-feature-4": "Aufgabenlistenverwaltung (Hinzufügen, Erledigen, Löschen)",
    "proj-8-feature-5": "Dauerhafte Datenspeicherung mit Local Storage",
    "proj-8-feature-6": "YouTube-API-basierter Musik-Player",
    "proj-8-feature-7": "Wiedergabelistenverwaltung (Abspielen, Pause, vorheriger/nächster Titel)",
    "proj-8-feature-8": "Zufälliges Zitat-Anzeigesystem",
    "proj-8-feature-9": "Google-Suche-Integration",
    "proj-8-feature-10": "Personalisierte Begrüßungen je nach Tageszeit",
    "proj-8-feature-11": "Automatischer Wechsel des Hintergrundbildes je nach Tageszeit",
    "proj-8-feature-12": "Benutzernamen-Einstellung und Abmeldefunktion",
    "proj-8-feature-13": "Responsives Design und Animationseffekte",
    "proj-8-challenge": "Integration mehrerer APIs und Zustandsverwaltung mit Local Storage, Echtzeit-Datensynchronisation.",
    "proj-8-solution": "Stabile Zustandsverwaltung mit einer modularisierten JavaScript-Struktur und ereignisbasierter Programmierung.",
    "proj-8-role": "Full-Stack-Entwickler",
    "proj-9-title": "Campingplatz-Verwaltungssystem",
    "proj-9-desc": "Eine Webanwendung zur Registrierung, Anzeige, Änderung und Löschung von Campingplatzinformationen sowie ein Bewertungssystem.",
    "proj-9-short": "Integrierte Campingplatz-Verwaltungsplattform.",
    "proj-9-overview": "Eine Webanwendung zur Registrierung und Verwaltung von Campingplatzinformationen. Beinhaltet Benutzerauthentifizierung, CRUD-Funktionen für Campingplätze und ein Bewertungssystem.",
    "proj-9-feature-1": "Benutzerregistrierung/Anmeldung/Abmeldung",
    "proj-9-feature-2": "Registrierung von Campingplatzinformationen (Titel, Standort, Preis, Beschreibung, Foto)",
    "proj-9-feature-3": "Anzeige von Campingplatzlisten und Detailansicht",
    "proj-9-feature-4": "Änderung und Löschung von Campingplatzinformationen",
    "proj-9-feature-5": "Verwaltung der Autorenrechte (nur eigene Beiträge können geändert/gelöscht werden)",
    "proj-9-feature-6": "Bewertungssystem (Bewertung und Textbewertung)",
    "proj-9-feature-7": "Responsives Webdesign (Bootstrap 5)",
    "proj-9-feature-8": "Benutzerfeedback durch Flash-Nachrichten",
    "proj-9-feature-9": "Sitzungsbasiertes Authentifizierungssystem",
    "proj-9-challenge": "Implementierung eines Benutzerauthentifizierungssystems und Berechtigungsverwaltung, Verarbeitung relationaler Daten in MongoDB.",
    "proj-9-solution": "Aufbau eines Authentifizierungssystems mit Passport.js und Optimierung der Abfrage relationaler Daten mit Mongoose populate.",
    "proj-9-role": "Full-Stack-Entwickler",
    
    // Project Badge Labels
    "badge-main": "Hauptprojekt",
    "badge-latest": "Neuestes Projekt", 
    "badge-side": "Nebenprojekt",
    "badge-completed": "Abgeschlossen",
    "badge-in-progress": "In Arbeit"
  },
  ko: {
    // Welcome Page
    'w-0-1': '포트폴리오에 오신 것을 환영합니다.',
    'w-0-2': '언어를 변경하시려면 국가 아이콘을 클릭하세요.',
    'w-0-3': '테마를 선택해주세요.',
    'w-1': '시작하려면 선호하는 테마를 선택하세요',
    'w-2': '라이트 모드',
    'w-3': '낮 시간 사용에 완벽한 깔끔하고 밝은 인터페이스',
    'w-4': '다크 모드',
    'w-5': '눈에 편안하고 어두운 환경에 완벽한 모드',
    'w-6': '언제든지 앱에서 이 설정을 변경할 수 있습니다',
    'w-7': '감지된 언어:',
    'w-8': '닫기',

    'h-1': '포트폴리오',
    
    // Main Page
    'm-0': '  안녕하세요',
    'm-0-0': '프론트엔드 개발자 유현우 입니다',
    'm-0-1': '알아보기 까지  ',
    'm-0-2': '✓ 완료됨',
    'm-0-3': '스와이프하여 시작',
    'm-1': '뛰어난 디지털 경험을 주고 개발을 설계하는것을 좋아합니다.',
    'm-2': '내 작품 보기',
    'm-3': '이력서 다운로드',
    'm-4': '프로젝트',
    'm-5': '수상',
    'm-6': '만족한 클라이언트',
    'm-7': '년 경력',
    'm-8': '주요 프로젝트',
    'm-9': '기술 & 도구',
    'm-10': '함께 일해요',
    'm-11': '프로젝트 아이디어가 있으신가요? 듣고 싶습니다. 메시지를 보내주시면 아이디어를 현실로 만드는 방법에 대해 논의해보겠습니다.',

    
    'DES-0': '유현우',
    'DES-5': '스택',
    
    // Contact Section
    'c-0': '연락하기',
    'c-1': '이름 *',
    'c-2': '이메일 *',
    'c-3': '전화번호 (선택사항)',
    'c-4': '메시지 *',
    'c-5': '전송하기',
    'c-6': '전송 중...',
    'c-7': '메시지가 성공적으로 전송되었습니다! 빠른 시일 내에 답변드리겠습니다.',
    'c-8': '전송 중 오류가 발생했습니다. 다시 시도해주세요.',
    'c-9': '이름을 입력해주세요',
    'c-10': '이메일을 입력해주세요',
    'c-11': '전화번호를 입력해주세요',
    'c-12': '메시지를 입력해주세요',
    'c-13': '선택사항',
    'c-14': 'AWS Lambda Function 실행 중...',
    'scroll-to-top': '맨 위로',
    
    // Projects Section
    'p-0': '전체',
    'p-1': '메인',
    'p-2': '사이드',
    'p-3': '완료',
    'p-4': '진행중',
    'p-5': '계획',
    'p-6': '자세히 보기',
    'p-7': 'GitHub 코드 보기',
    'p-8': '라이브 데모 보기',
    'p-9': '더보기',
    'p-10': '접기',
    
    // Projects Section Additional Keys
    'p-11': 'Projects',
    'p-12': '다양한 프로젝트를 확인해보세요',
    'p-13': '프로젝트 종류',
    'p-14': '완성 상태',
    'p-15': '개 더',
    
    // Project Detail Modal Keys
    'pd-1': 'GitHub 코드 보기',
    'pd-2': '라이브 데모 보기',
    'pd-3': '프로젝트 정보',
    'pd-4': '개발 인원:',
    'pd-5': '명',
    'pd-6': '역할:',
    'pd-7': '기술 스택',
    'pd-8': '프로젝트 개요',
    'pd-9': '주요 기능',
    'pd-10': '도전 과제',
    'pd-11': '해결 방법',
    
    // Project Badge Labels
    'badge-main': '메인 프로젝트',
    'badge-latest': '최신 프로젝트',
    'badge-side': '사이드 프로젝트',
    'badge-completed': '완성',
    'badge-in-progress': '제작중',
    
    // Blog Section
    'b-0': '최신 블로그 포스트',
    'b-1': '더 읽기',
    'b-2': '자세한 내용은 Notion 바로가기를 클릭해주세요',
    'b-3': 'Notion 바로가기',
    
    // Stack Section
    's-0': '언어 및 프레임워크',
    's-1': '라이브러리',
    's-2': '환경 및 배포',
    's-3': '디자인 및 협업',
    
    // Stack Filter Labels
    'stack-all': '전체',
    'stack-language': '언어 및 프레임워크',
    'stack-library': '라이브러리',
    'stack-deployment': '환경 및 배포',
    'stack-design': '디자인 및 협업',
    
    // Project Data (Korean)
    'proj-1-title': 'The Clipo Project',
    'proj-1-desc': 'React와 Tailwind CSS TypeScript를 사용한 소셜미디어 플랫폼 포트폴리오',
    'proj-1-short': '개인 포트폴리오 웹사이트',
    'proj-1-overview': '개인 포트폴리오를 위한 반응형 웹사이트로, 다크/라이트 모드, Access Token, Refresh Token 포함합니다. 친구와 한번 소셜미디어를 만든다는 생각을 가지고 한번 열심히 현업하듯이 만들어 보았습니다.',
    'proj-1-feature-1': '인증 및 토큰 관리 시스템',
    'proj-1-feature-2': 'Redux 기반 다중 중첩 모달 시스템',
    'proj-1-feature-3': '소셜 미디어 핵심 기능',
    'proj-1-feature-4': 'UI 컴포넌트 및 디자인 시스템',
    'proj-1-feature-5': '데이터 관리 및 상태 관리',
    'proj-1-feature-6': '실시간 기능',
    'proj-1-challenge': '낙관적 업데이트와 데이터 동기화/ 백엔드와 전체적인 협업',
    'proj-1-solution': 'React-query를 활용하여 네트워크 오류시 전의 쿼리를 가져와 동기화',
    'proj-1-role': '프론트엔드 / 기획자',

    // Project 2 - Football Video Automation
    'proj-2-title': '축구 영상 자동화 시스템',
    'proj-2-desc': 'AWS Lambda와 Python 기반 Movie.py를 활용한 축구 영상 자동화 프로젝트.',
    'proj-2-overview': '축구를 좋아해서 만든 동영상 자동화 시스템으로 기획 구상을 하여 이후에 개발 시작, 일주일에 한번 실행되는 동영상 자동화 시스템 입니다. 이후에 받아온 경기일정을 기반으로 Aws Lamda 를 예약하여 이후에 Telegram Bot으로 경기 데이터를 fetch해 옵니다.',
    'proj-2-feature-1': 'Football Api 데이터 패칭',
    'proj-2-feature-2': 'Python 데이터 가공 및 Telegram Bot 연동',
    'proj-2-feature-3': 'Aws Lamda 예약 및 실행',
    'proj-2-feature-4': 'Aws S3 파일 저장',
    'proj-2-feature-5': 'Google Spreadsheet 연동',
    'proj-2-feature-6': 'Movie.py 동영상 자동화',
    'proj-2-feature-7': 'Youtube Api 연동',
    'proj-2-challenge': 'Movie.py 패키지 적응, Aws Step Function run time error handling',
    'proj-2-solution': 'Movie.py Offical Documentation을 참고하여 적응, Step Function에서 발생하는 error 종류 파악 및 runtime error 처리',
    'proj-2-role': '1인 개발',

    // Project 3 - Calendar Project
    'proj-3-title': '캘린더 자동화',
    'proj-3-desc': '자동화된 캘린더 플랫폼',
    'proj-3-overview': '완전한 기능을 갖춘 온라인 쇼핑몰 플랫폼으로, 사용자 인증, 결제 시스템, 관리자 대시보드를 포함합니다.',
    'proj-3-feature-1': '사용자 인증 및 권한 관리',
    'proj-3-feature-2': '상품 검색 및 필터링',
    'proj-3-feature-3': '장바구니 및 위시리스트',
    'proj-3-feature-4': 'Stripe 결제 시스템',
    'proj-3-feature-5': '관리자 대시보드',
    'proj-3-feature-6': '실시간 재고 관리',
    'proj-3-challenge': '대용량 트래픽 처리와 결제 보안',
    'proj-3-solution': 'Redis 캐싱과 Stripe 보안 API를 활용한 안전한 결제 시스템 구축',
    'proj-3-role': '프론트 개발자',

    // Project 4 - Job Scraper
    'proj-4-title': '파이썬 웹 채용 스크래퍼',
    'proj-4-desc': '여러 채용 사이트의 공고를 동시에 검색하고 필터링하는 통합 웹 스크래퍼.',
    'proj-4-overview': '한국 및 해외 구직사이트에서 채용공고를 실시간으로 수집하고 통합 검색할 수 있는 웹 애플리케이션',
    'proj-4-feature-1': '4개 구직사이트 통합 검색 (원티드, 사람인, RemoteOK, WeWorkRemotely)',
    'proj-4-feature-2': '사이트별 선택적 검색 기능',
    'proj-4-feature-3': '지역별 필터링 (서울, 경기, 인천 등)',
    'proj-4-feature-4': '실시간 채용공고 수집',
    'proj-4-feature-5': 'CSV 파일 다운로드 기능',
    'proj-4-feature-6': '모바일 반응형 디자인',
    'proj-4-feature-7': '동적 웹 스크래핑 (Selenium)',
    'proj-4-feature-8': 'API 기반 데이터 수집 (Wanted, RemoteOK)',
    'proj-4-feature-9': '사이트별 통계 및 필터링',
    'proj-4-feature-10': '검색 결과 실시간 업데이트',
    'proj-4-challenge': '다양한 사이트의 접근 제한과 동적 콘텐츠 처리, 안정적인 데이터 수집',
    'proj-4-solution': 'Selenium과 requests의 하이브리드 접근법, 에러 핸들링 및 폴백 메커니즘 구현',
    'proj-4-role': '풀스택 개발자',

    // Project 5 - Random Chord Practice
    'proj-5-title': '랜덤 코드 연습 앱',
    'proj-5-desc': '음악 연습을 위한 모던하고 사용자 친화적인 랜덤 코드 생성기.',
    'proj-5-overview': '음악가들을 위한 랜덤 코드 연습 앱으로, 다양한 코드 타입과 템포 설정을 통해 체계적인 음악 연습을 제공합니다. Web Speech API를 활용한 음성 안내와 실시간 템포 조절 기능을 포함합니다.',
    'proj-5-feature-1': '랜덤 코드 생성 및 연습',
    'proj-5-feature-2': '17개 음표 지원 (C, Db, D, Eb, E, F, Gb, G, Ab, A, Bb, B, C#, D#, F#, G#, A#)',
    'proj-5-feature-3': '다양한 코드 타입 (Maj7, min7, 7, sus4, add9 등 50+ 종류)',
    'proj-5-feature-4': '실시간 템포 조절 (1-220 BPM)',
    'proj-5-feature-5': '박자 시각화 (4박자 점 애니메이션)',
    'proj-5-feature-6': '음성 안내 시스템 (TTS)',
    'proj-5-feature-7': '커스텀 코드 추가/제거',
    'proj-5-feature-8': '설정 저장 (Local Storage)',
    'proj-5-feature-9': '반응형 디자인',
    'proj-5-feature-10': 'A/B 폼 패턴 선택',
    'proj-5-challenge': '복잡한 페이지 네비게이션과 실시간 템포 변경 시 박자 동기화 유지',
    'proj-5-solution': '3-컴포넌트 구조(제목/메인/설정)와 인터벌 기반 박자 애니메이션으로 안정적인 상태 관리 구현',
    'proj-5-role': '풀스택 개발자',

    // Project 6 - The Area
    'proj-6-title': 'The Area - 크리에이티브 플랫폼',
    'proj-6-desc': '음악과 비주얼, 크리에이터를 위한 종합 크리에이티브 플랫폼.',
    'proj-6-overview': '음악, 비주얼 아트, 크리에이터들을 위한 종합 크리에이티브 플랫폼',
    'proj-6-feature-1': '비디오 배경과 로고 애니메이션',
    'proj-6-feature-2': '음악 비디오 플레이어',
    'proj-6-feature-3': '크리에이터 프로필 갤러리',
    'proj-6-feature-4': 'MV 갤러리 시스템',
    'proj-6-feature-5': '반응형 디자인',
    'proj-6-feature-6': '페이지 라우팅 시스템',
    'proj-6-challenge': '복잡한 애니메이션과 비디오 처리, 반응형 디자인 구현',
    'proj-6-solution': 'CSS 애니메이션과 React 상태 관리를 통한 동적 UI 구현',
    'proj-6-role': '풀스택 개발자',

    // Project 7 - Cocoa Talk
    'proj-7-title': '축구 테마 카카오톡 웹사이트',
    'proj-7-desc': 'HTML, CSS, JavaScript로 제작한 축구 테마의 카카오톡 클론 모바일 웹사이트.',
    'proj-7-overview': '카카오톡의 UI/UX를 모방하여 만든 웹사이트로, 축구 테마가 적용된 채팅 애플리케이션입니다. 모바일 우선 설계로 반응형 웹 디자인을 구현했습니다.',
    'proj-7-feature-1': '실시간 시계 표시 기능',
    'proj-7-feature-2': '모바일 반응형 디자인',
    'proj-7-feature-3': '축구 경기 일정 및 라이브 스트리밍 섹션',
    'proj-7-feature-4': '채팅방 목록 및 개별 채팅방',
    'proj-7-feature-5': '프로필 페이지 (축구 선수 정보 포함)',
    'proj-7-feature-6': '커뮤니티 및 검색 기능',
    'proj-7-feature-7': 'Font Awesome 아이콘 활용',
    'proj-7-feature-8': 'CSS 애니메이션 효과',
    'proj-7-feature-9': '모바일 화면 크기 제한 기능',
    'proj-7-challenge': '모바일 우선 설계와 카카오톡의 복잡한 UI 구조를 웹으로 구현하는 것',
    'proj-7-solution': 'CSS Grid와 Flexbox를 활용한 레이아웃 구성, JavaScript를 통한 실시간 기능 구현, 모바일 화면 크기 감지 기능 추가',
    'proj-7-role': '풀스택 웹 개발자',

    // Project 8 - Momentum Dashboard
    'proj-8-title': 'Momentum 대시보드',
    'proj-8-desc': '개인 생산성을 높이기 위한 올인원 대시보드 웹 애플리케이션.',
    'proj-8-overview': '개인 생산성 향상을 위한 올인원 대시보드로, 실시간 시계, 날씨 정보, 할 일 관리, 음악 플레이어, 명언 표시, 구글 검색 기능을 통합한 현대적인 웹 애플리케이션입니다. 사용자 개인화와 반응형 디자인을 통해 최적의 사용자 경험을 제공합니다.',
    'proj-8-feature-1': '실시간 디지털 시계 및 날짜 표시',
    'proj-8-feature-2': 'Geolocation 기반 현재 위치 날씨 정보',
    'proj-8-feature-3': 'OpenWeather API 연동 (온도, 습도, 체감온도 등)',
    'proj-8-feature-4': '할 일 목록 관리 (추가, 완료, 삭제)',
    'proj-8-feature-5': 'Local Storage를 활용한 데이터 영구 저장',
    'proj-8-feature-6': 'YouTube API 기반 음악 플레이어',
    'proj-8-feature-7': '재생목록 관리 (재생, 일시정지, 이전/다음 곡)',
    'proj-8-feature-8': '랜덤 명언 표시 시스템',
    'proj-8-feature-9': 'Google 검색 통합',
    'proj-8-feature-10': '시간대별 맞춤 인사말',
    'proj-8-feature-11': '시간대별 배경 이미지 자동 변경',
    'proj-8-feature-12': '사용자 이름 설정 및 로그아웃 기능',
    'proj-8-feature-13': '반응형 디자인 및 애니메이션 효과',
    'proj-8-challenge': '다중 API 연동과 Local Storage 상태 관리, 실시간 데이터 동기화',
    'proj-8-solution': '모듈화된 JavaScript 구조와 이벤트 기반 프로그래밍으로 안정적인 상태 관리 구현',
    'proj-8-role': '풀스택 개발자',

    // Project 9 - Campground
    'proj-9-title': '캠핑장 관리 시스템',
    'proj-9-desc': '캠핑장 정보를 등록하고 조회, 수정, 삭제하며 리뷰를 제공하는 웹 애플리케이션.',
    'proj-9-overview': '캠핑장 정보를 등록하고 관리할 수 있는 웹 애플리케이션입니다. 사용자 인증, 캠핑장 CRUD 기능, 리뷰 시스템을 포함합니다.',
    'proj-9-feature-1': '사용자 회원가입/로그인/로그아웃',
    'proj-9-feature-2': '캠핑장 정보 등록 (제목, 위치, 가격, 설명, 사진)',
    'proj-9-feature-3': '캠핑장 목록 조회 및 상세 보기',
    'proj-9-feature-4': '캠핑장 정보 수정 및 삭제',
    'proj-9-feature-5': '작성자 권한 관리 (본인 글만 수정/삭제 가능)',
    'proj-9-feature-6': '리뷰 시스템 (평점 및 텍스트 리뷰)',
    'proj-9-feature-7': '반응형 웹 디자인 (Bootstrap 5)',
    'proj-9-feature-8': '플래시 메시지를 통한 사용자 피드백',
    'proj-9-feature-9': '세션 기반 인증 시스템',
    'proj-9-challenge': '사용자 인증 시스템 구현과 권한 관리, MongoDB 관계형 데이터 처리',
    'proj-9-solution': 'Passport.js를 활용한 인증 시스템 구축과 Mongoose populate를 통한 관계형 데이터 조회 최적화',
    'proj-9-role': '풀스택 개발자',
    
    // About Me Section
    'about-title': 'About Me',
    'experience-title': '💼 경력 (Experience)',
    'education-title': '🎓 학력 (Education)',
    'experience-btn': '💼 경력',
    'education-btn': '🎓 학력',
    
    // Experience Data
    'exp-1-company': 'Coboct (프랑스)',
    'exp-1-position': '홈페이지 리뉴얼 인턴',
    'exp-1-period': '2023.09 - 2023.12 (4개월)',
    'exp-1-desc-1': 'react.js와 ModuleCSS를 활용한 프론트엔드 UI/UX 개선',
    'exp-1-desc-2': '반응형 웹 디자인 적용',
    'exp-1-desc-3': 'Three.js를 활용한 3D 효과 적용 시도',
    
    'exp-2-company': '알서포트 (Rsupport)',
    'exp-2-position': 'QA Engineer',
    'exp-2-period': '2021.06 - 2022.12 (1년 6개월)',
    'exp-2-desc-1': '개발 기획 회의 참여',
    'exp-2-desc-2': '테스트 케이스 작성 인증',
    'exp-2-desc-3': '자바 셀레니움 자동화 테스트 스크립트 작성 및 유지보수 참여',
    
    'exp-3-company': '대한민국 육군',
    'exp-3-position': '8사단 만기 전역',
    'exp-3-period': '2019.04 - 2021.10',
    'exp-3-desc-1': '분대장 임무 수행을 통한 리더십 및 책임감 함양',
    'exp-3-desc-2': '원활한 소통 능력을 바탕으로 한 팀워크 증진',
    
    // Education Data
    'edu-1-school': '고려사이버대학교',
    'edu-1-major': '소프트웨어응용학과 졸업 (2021-2024)',
    'edu-2-school': '한림대학교',
    'edu-2-major': '경제학과 중퇴 (2018-2019)',
    
    // Blog Data
    'blog-1-title': 'AccessToken RefreshToken 구현',
    'blog-1-desc': '엑세스 토큰과 리프레쉬 토큰을 구현하여 jwt 인증 절차를 알아 봅니다. 여러가지 방법중에서 쿠키값에 저장을한뒤 만료되면 재할당을 동작으로 refreshToken 을 사용한다',
    'blog-2-title': 'Mongoose 를 이용하여 MongoDb data 구조화',
    'blog-2-desc': 'Campingground 작업도중 node.js 와 mongoDb 의 데이터 객체를 파싱해오는 mongoose를 알게되었다. 몽구스는 mongoDb의 데이터를 활용하기 쉬운 객체 형태로 파싱하기 쉽게 해주는 모듈이다',
    'blog-3-title': '중첩 모달 구현하기',
    'blog-3-desc': 'Redux 의 초기값을 배열로 변경하여 z-index를 알맞게 분배하여 중첩모달을 구현합니다.',
    
    // Rotating Text
    'rotating-texts': '창의적인,열정적인,갈망하는,도전하는',
  },
};

export default LanguagePack;
